export interface BugExercise {
  id: string;
  emoji: string;
  title: string;
  title_en?: string;
  difficulty: "Facile" | "Moyen" | "Difficile";
  difficultyColor: string;
  description: string;
  description_en?: string;
  buggyCode: string;
  buggyCode_en?: string;
  fixedCode: string;
  fixedCode_en?: string;
  expectedOutput: string;
  hint: string;
  hint_en?: string;
  explanation: string;
  explanation_en?: string;
}

export const BUG_EXERCISES: BugExercise[] = [
  {
    id: "print_typo",
    emoji: "👋",
    title: "Faute de frappe",
    title_en: "Typo",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Ce code devrait afficher « Bonjour Python ! » mais il plante. Trouve et corrige l'erreur !",
    description_en: "This code should display 'Hello Python!' but it crashes. Find and fix the bug!",
    buggyCode: "prind(\"Bonjour Python !\")",
    buggyCode_en: "prind(\"Hello Python!\")",
    fixedCode: "print(\"Bonjour Python !\")",
    fixedCode_en: "print(\"Hello Python!\")",
    expectedOutput: "Bonjour Python !",
    hint: "Regarde le nom de la fonction d'affichage. Est-il bien écrit ?",
    hint_en: "Look at the name of the display function. Is it spelled correctly?",
    explanation: "print() était mal orthographié en prind(). Python ne connaît pas prind !",
    explanation_en: "print() was misspelled as prind(). Python doesn't know prind!",
  },
  {
    id: "indentation",
    emoji: "📐",
    title: "Problème d'indentation",
    title_en: "Indentation issue",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Ce code devrait afficher les nombres de 1 à 3, mais il y a une erreur d'indentation.",
    description_en: "This code should display numbers from 1 to 3, but there's an indentation error.",
    buggyCode: "for i in range(1, 4):\nprint(i)",
    buggyCode_en: "for i in range(1, 4):\nprint(i)",
    fixedCode: "for i in range(1, 4):\n    print(i)",
    fixedCode_en: "for i in range(1, 4):\n    print(i)",
    expectedOutput: "1\n2\n3",
    hint: "En Python, le code dans une boucle doit être décalé vers la droite (indentation).",
    hint_en: "In Python, code inside a loop must be indented (shifted right).",
    explanation: "Après un for:, le bloc de code doit être indenté avec 4 espaces.",
    explanation_en: "After a for:, the code block must be indented with 4 spaces.",
  },
  {
    id: "off_by_one",
    emoji: "🔢",
    title: "Erreur de comptage",
    title_en: "Counting error",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Ce code devrait afficher les nombres de 1 à 5, mais il n'en affiche que 4.",
    description_en: "This code should display numbers from 1 to 5, but only shows 4.",
    buggyCode: "for i in range(1, 5):\n    print(i)",
    buggyCode_en: "for i in range(1, 5):\n    print(i)",
    fixedCode: "for i in range(1, 6):\n    print(i)",
    fixedCode_en: "for i in range(1, 6):\n    print(i)",
    expectedOutput: "1\n2\n3\n4\n5",
    hint: "range(a, b) s'arrête avant b. Pour aller jusqu'à 5, il faut range(1, 6).",
    hint_en: "range(a, b) stops before b. To go up to 5, use range(1, 6).",
    explanation: "range(1, 5) génère 1, 2, 3, 4. Pour inclure 5, il faut range(1, 6).",
    explanation_en: "range(1, 5) generates 1, 2, 3, 4. To include 5, use range(1, 6).",
  },
  {
    id: "wrong_operator",
    emoji: "➕",
    title: "Mauvais opérateur",
    title_en: "Wrong operator",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Ce code devrait vérifier si x est égal à 10, mais la condition est toujours fausse.",
    description_en: "This code should check if x equals 10, but the condition is always false.",
    buggyCode: "x = 10\nif x = 10:\n    print(\"x vaut 10\")",
    buggyCode_en: "x = 10\nif x = 10:\n    print(\"x is 10\")",
    fixedCode: "x = 10\nif x == 10:\n    print(\"x vaut 10\")",
    fixedCode_en: "x = 10\nif x == 10:\n    print(\"x is 10\")",
    expectedOutput: "x vaut 10",
    hint: "Pour comparer deux valeurs en Python, on utilise == (double égal) et non = (simple égal).",
    hint_en: "To compare two values in Python, use == (double equals), not = (single equals).",
    explanation: "= sert à assigner une valeur. == sert à comparer. if x = 10 est une erreur de syntaxe !",
    explanation_en: "= assigns a value. == compares. if x = 10 is a syntax error!",
  },
  {
    id: "string_concat",
    emoji: "🔗",
    title: "Concaténation cassée",
    title_en: "Broken concatenation",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-500",
    description: "Ce code devrait afficher « J'ai 12 ans », mais il plante. Trouve le bug !",
    description_en: "This code should display 'I am 12 years old' but it crashes. Find the bug!",
    buggyCode: "age = 12\nprint(\"J'ai \" + age + \" ans\")",
    buggyCode_en: "age = 12\nprint(\"I am \" + age + \" years old\")",
    fixedCode: "age = 12\nprint(\"J'ai \" + str(age) + \" ans\")",
    fixedCode_en: "age = 12\nprint(\"I am \" + str(age) + \" years old\")",
    expectedOutput: "J'ai 12 ans",
    hint: "On ne peut pas concaténer directement un texte et un nombre. Il faut convertir le nombre en texte.",
    hint_en: "You can't directly concatenate text and a number. You need to convert the number to text.",
    explanation: "str(age) convertit le nombre 12 en texte \"12\" pour pouvoir le coller avec d'autres chaînes.",
    explanation_en: "str(age) converts the number 12 to the string \"12\" so it can be joined with other strings.",
  },
  {
    id: "list_index",
    emoji: "📋",
    title: "Index hors limites",
    title_en: "Index out of bounds",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-500",
    description: "Ce code devrait afficher le dernier fruit de la liste, mais il plante avec une erreur.",
    description_en: "This code should display the last fruit in the list, but it crashes with an error.",
    buggyCode: "fruits = [\"pomme\", \"banane\", \"cerise\"]\nprint(fruits[3])",
    buggyCode_en: "fruits = [\"apple\", \"banana\", \"cherry\"]\nprint(fruits[3])",
    fixedCode: "fruits = [\"pomme\", \"banane\", \"cerise\"]\nprint(fruits[2])",
    fixedCode_en: "fruits = [\"apple\", \"banana\", \"cherry\"]\nprint(fruits[2])",
    expectedOutput: "cerise",
    hint: "Les indices commencent à 0. Une liste de 3 éléments a les indices 0, 1 et 2.",
    hint_en: "Indices start at 0. A list of 3 elements has indices 0, 1 and 2.",
    explanation: "fruits[3] est hors limites car les indices vont de 0 à 2. Le dernier élément est fruits[2].",
    explanation_en: "fruits[3] is out of bounds because indices go from 0 to 2. The last element is fruits[2].",
  },
  {
    id: "infinite_while",
    emoji: "🔄",
    title: "Boucle infinie cachée",
    title_en: "Hidden infinite loop",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-500",
    description: "Ce code devrait compter de 1 à 3, mais il tourne à l'infini. Trouve le bug !",
    description_en: "This code should count from 1 to 3, but it loops forever. Find the bug!",
    buggyCode: "i = 1\nwhile i <= 3:\n    print(i)\n    i = i - 1",
    buggyCode_en: "i = 1\nwhile i <= 3:\n    print(i)\n    i = i - 1",
    fixedCode: "i = 1\nwhile i <= 3:\n    print(i)\n    i = i + 1",
    fixedCode_en: "i = 1\nwhile i <= 3:\n    print(i)\n    i = i + 1",
    expectedOutput: "1\n2\n3",
    hint: "La variable i doit augmenter à chaque tour pour que la boucle s'arrête un jour.",
    hint_en: "The variable i must increase each iteration for the loop to eventually stop.",
    explanation: "i = i - 1 diminue i, donc la condition i <= 3 reste toujours vraie → boucle infinie ! Il faut i = i + 1.",
    explanation_en: "i = i - 1 decreases i, so the condition i <= 3 stays true forever → infinite loop! Use i = i + 1.",
  },
  {
    id: "function_return",
    emoji: "🔧",
    title: "Valeur non retournée",
    title_en: "Missing return value",
    difficulty: "Difficile",
    difficultyColor: "from-red-400 to-rose-500",
    description: "La fonction double() devrait retourner le double d'un nombre, mais elle retourne None.",
    description_en: "The double() function should return twice a number, but it returns None.",
    buggyCode: "def double(n):\n    resultat = n * 2\n\nprint(double(5))",
    buggyCode_en: "def double(n):\n    result = n * 2\n\nprint(double(5))",
    fixedCode: "def double(n):\n    resultat = n * 2\n    return resultat\n\nprint(double(5))",
    fixedCode_en: "def double(n):\n    result = n * 2\n    return result\n\nprint(double(5))",
    expectedOutput: "10",
    hint: "Une fonction doit utiliser return pour renvoyer sa valeur. Sans return, elle renvoie None.",
    hint_en: "A function must use return to send back its value. Without return, it returns None.",
    explanation: "Sans return, la fonction calcule le résultat mais ne le renvoie pas. print(None) affiche 'None'.",
    explanation_en: "Without return, the function computes the result but doesn't send it back. print(None) shows 'None'.",
  },
  {
    id: "dict_key",
    emoji: "📦",
    title: "Clé de dictionnaire",
    title_en: "Dictionary key",
    difficulty: "Difficile",
    difficultyColor: "from-red-400 to-rose-500",
    description: "Ce code devrait afficher l'âge de Marie, mais il plante avec une KeyError.",
    description_en: "This code should display Marie's age, but it crashes with a KeyError.",
    buggyCode: "personne = {\"nom\": \"Marie\", \"age\": 14}\nprint(personne[\"Age\"])",
    buggyCode_en: "person = {\"name\": \"Marie\", \"age\": 14}\nprint(person[\"Age\"])",
    fixedCode: "personne = {\"nom\": \"Marie\", \"age\": 14}\nprint(personne[\"age\"])",
    fixedCode_en: "person = {\"name\": \"Marie\", \"age\": 14}\nprint(person[\"age\"])",
    expectedOutput: "14",
    hint: "Les clés d'un dictionnaire sont sensibles à la casse. \"age\" et \"Age\" sont différents !",
    hint_en: "Dictionary keys are case-sensitive. \"age\" and \"Age\" are different!",
    explanation: "La clé est \"age\" (minuscule) mais on accède à \"Age\" (majuscule). Python est sensible à la casse.",
    explanation_en: "The key is \"age\" (lowercase) but we access \"Age\" (uppercase). Python is case-sensitive.",
  },
  {
    id: "scope_bug",
    emoji: "🌍",
    title: "Variable hors portée",
    title_en: "Variable out of scope",
    difficulty: "Difficile",
    difficultyColor: "from-red-400 to-rose-500",
    description: "Ce code devrait afficher le total, mais la variable total n'est pas accessible.",
    description_en: "This code should display the total, but the total variable isn't accessible.",
    buggyCode: "def calculer():\n    total = 0\n    for i in range(1, 6):\n        total += i\n\ncalculer()\nprint(total)",
    buggyCode_en: "def calculate():\n    total = 0\n    for i in range(1, 6):\n        total += i\n\ncalculate()\nprint(total)",
    fixedCode: "def calculer():\n    total = 0\n    for i in range(1, 6):\n        total += i\n    return total\n\nresultat = calculer()\nprint(resultat)",
    fixedCode_en: "def calculate():\n    total = 0\n    for i in range(1, 6):\n        total += i\n    return total\n\nresult = calculate()\nprint(result)",
    expectedOutput: "15",
    hint: "Les variables créées dans une fonction n'existent que dans cette fonction. Il faut les retourner.",
    hint_en: "Variables created inside a function only exist inside that function. You need to return them.",
    explanation: "total est une variable locale à calculer(). En dehors, elle n'existe pas. Il faut return total et capturer le résultat.",
    explanation_en: "total is local to calculate(). Outside the function, it doesn't exist. Use return total and capture the result.",
  },
];

export function getBugExerciseById(id: string): BugExercise | undefined {
  return BUG_EXERCISES.find((e) => e.id === id);
}
