export interface Challenge {
  id: string;
  emoji: string;
  title: string;
  title_en?: string;
  difficulty: "Facile" | "Moyen" | "Difficile";
  difficultyColor: string;
  description: string;
  description_en?: string;
  starterCode: string;
  starterCode_en?: string;
  hint: string;
  hint_en?: string;
  expectedOutput: string;
  expectedOutput_en?: string;
  solutionCode: string;
  solutionCode_en?: string;
  minLevel: number; // niveau minimum recommandé (0–5)
  hints: [string, string, string]; // indices progressifs : vague → précis → quasi-solution
  hints_en?: [string, string, string];
}

export const CHALLENGES: Challenge[] = [
  // ── FACILE ──────────────────────────────────────────────────────────
  {
    id: "hello",
    emoji: "👋",
    title: "Dis bonjour !",
    title_en: "Say hello!",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Affiche exactement ce message :\nBonjour Python !",
    description_en: "Display exactly this message:\nHello Python!",
    starterCode: "# Affiche le bon message\n",
    starterCode_en: "# Display the right message\n",
    hint: "Utilise print() avec le texte exact entre guillemets.",
    hint_en: "Use print() with the exact text in quotes.",
    hints: [
      "Pense au mot magique de Python pour afficher du texte à l'écran.",
      "Utilise print() avec le texte exact entre guillemets.",
      'Écris : print("Bonjour Python !")',
    ],
    hints_en: [
      "Think of the Python keyword to display text on screen.",
      "Use print() with the exact text in quotes.",
      'Write: print("Hello Python!")',
    ],
    expectedOutput: "Bonjour Python !",
    expectedOutput_en: "Hello Python!",
    solutionCode: 'print("Bonjour Python !")',
    solutionCode_en: 'print("Hello Python!")',
    minLevel: 0,
  },
  {
    id: "even_odd",
    emoji: "🔢",
    title: "Pair ou impair",
    title_en: "Even or odd",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Le nombre 42 est-il pair ou impair ?\nAffiche 'pair' ou 'impair'.",
    description_en: "Is the number 42 even or odd?\nDisplay 'even' or 'odd'.",
    starterCode: "n = 42\n# Affiche pair ou impair\n",
    starterCode_en: "n = 42\n# Display even or odd\n",
    hint: "Utilise le modulo % : si n % 2 == 0 alors c'est pair.",
    hint_en: "Use modulo %: if n % 2 == 0 then it's even.",
    hints: [
      "Il existe un opérateur en Python qui donne le reste d'une division.",
      "Utilise le modulo % : si n % 2 == 0 alors c'est pair.",
      'if n % 2 == 0:\n    print("pair")\nelse:\n    print("impair")',
    ],
    hints_en: [
      "There's an operator in Python that gives the remainder of a division.",
      "Use modulo %: if n % 2 == 0 then it's even.",
      'if n % 2 == 0:\n    print("even")\nelse:\n    print("odd")',
    ],
    expectedOutput: "pair",
    expectedOutput_en: "even",
    solutionCode: "n = 42\nif n % 2 == 0:\n    print(\"pair\")\nelse:\n    print(\"impair\")",
    solutionCode_en: 'n = 42\nif n % 2 == 0:\n    print("even")\nelse:\n    print("odd")',
    minLevel: 1,
  },
  {
    id: "sum",
    emoji: "➕",
    title: "La somme des 10",
    title_en: "Sum of 10",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Calcule et affiche la somme de tous les nombres de 1 à 10.\n(1 + 2 + 3 + … + 10)",
    description_en: "Calculate and display the sum of all numbers from 1 to 10.\n(1 + 2 + 3 + … + 10)",
    starterCode: "# Affiche la somme de 1 à 10\n",
    starterCode_en: "# Display the sum from 1 to 10\n",
    hint: "Tu peux utiliser sum(range(1, 11)) ou une boucle for.",
    hint_en: "You can use sum(range(1, 11)) or a for loop.",
    hints: [
      "Pense à une fonction Python qui fait une somme, ou à une boucle qui accumule.",
      "Tu peux utiliser sum(range(1, 11)) ou une boucle for.",
      "print(sum(range(1, 11)))",
    ],
    hints_en: [
      "Think of a Python function that sums, or a loop that accumulates.",
      "You can use sum(range(1, 11)) or a for loop.",
      "print(sum(range(1, 11)))",
    ],
    expectedOutput: "55",
    solutionCode: "print(sum(range(1, 11)))",
    minLevel: 1,
  },
  {
    id: "vowels",
    emoji: "🔤",
    title: "Compte les voyelles",
    title_en: "Count the vowels",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Combien de voyelles (a, e, i, o, u, y) y a-t-il dans le mot 'programmation' ?\nAffiche ce nombre.",
    description_en: "How many vowels (a, e, i, o, u, y) are there in the word 'programmation'?\nDisplay that number.",
    starterCode: "mot = \"programmation\"\n# Compte les voyelles\n",
    starterCode_en: 'word = "programmation"\n# Count the vowels\n',
    hint: "Parcours chaque lettre avec une boucle for et vérifie si elle est dans 'aeiouy'.",
    hint_en: "Loop through each letter with a for loop and check if it's in 'aeiouy'.",
    hints: [
      "Parcours le mot lettre par lettre et vérifie si chaque lettre appartient à un groupe.",
      "Parcours chaque lettre avec une boucle for et vérifie si elle est dans 'aeiouy'.",
      "count = 0\nfor c in mot:\n    if c in 'aeiouy':\n        count += 1\nprint(count)",
    ],
    hints_en: [
      "Loop through the word letter by letter and check if each letter belongs to a group.",
      "Loop through each letter with a for loop and check if it's in 'aeiouy'.",
      "count = 0\nfor c in word:\n    if c in 'aeiouy':\n        count += 1\nprint(count)",
    ],
    expectedOutput: "5",
    solutionCode: "mot = \"programmation\"\ncount = sum(1 for c in mot if c in \"aeiouy\")\nprint(count)",
    solutionCode_en: 'word = "programmation"\ncount = sum(1 for c in word if c in "aeiouy")\nprint(count)',
    minLevel: 1,
  },
  {
    id: "fstring",
    emoji: "💬",
    title: "F-strings magiques",
    title_en: "Magic f-strings",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Utilise les variables prenom et age pour afficher ce message avec une f-string :\nBonjour, je m'appelle Alice et j'ai 14 ans.",
    description_en: "Use the variables name and age to display this message with an f-string:\nHello, my name is Alice and I am 14 years old.",
    starterCode: 'prenom = "Alice"\nage = 14\n# Affiche le message avec une f-string\n',
    starterCode_en: 'name = "Alice"\nage = 14\n# Display the message with an f-string\n',
    hint: "Écris f\"Bonjour, je m'appelle {prenom} et j'ai {age} ans.\"",
    hint_en: 'Write f"Hello, my name is {name} and I am {age} years old."',
    hints: [
      "Les f-strings en Python permettent d'insérer des variables directement dans du texte.",
      "Écris f\"Bonjour, je m'appelle {prenom} et j'ai {age} ans.\"",
      "print(f\"Bonjour, je m'appelle {prenom} et j'ai {age} ans.\")",
    ],
    hints_en: [
      "F-strings in Python let you insert variables directly into text.",
      'Write f"Hello, my name is {name} and I am {age} years old."',
      'print(f"Hello, my name is {name} and I am {age} years old.")',
    ],
    expectedOutput: "Bonjour, je m'appelle Alice et j'ai 14 ans.",
    expectedOutput_en: "Hello, my name is Alice and I am 14 years old.",
    solutionCode: "prenom = \"Alice\"\nage = 14\nprint(f\"Bonjour, je m'appelle {prenom} et j'ai {age} ans.\")",
    solutionCode_en: 'name = "Alice"\nage = 14\nprint(f"Hello, my name is {name} and I am {age} years old.")',
    minLevel: 1,
  },
  {
    id: "unique",
    emoji: "🎲",
    title: "Éléments uniques",
    title_en: "Unique elements",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Combien de langages différents y a-t-il dans cette liste ?\n(certains apparaissent plusieurs fois)\nAffiche juste le nombre.",
    description_en: "How many different programming languages are in this list?\n(some appear multiple times)\nDisplay just the number.",
    starterCode: 'langages = ["python", "java", "python", "c++", "java", "python"]\n# Affiche le nombre de langages uniques\n',
    starterCode_en: 'languages = ["python", "java", "python", "c++", "java", "python"]\n# Display the number of unique languages\n',
    hint: "set() supprime les doublons. len(set(langages)) donne le nombre d'éléments différents.",
    hint_en: "set() removes duplicates. len(set(languages)) gives the number of different elements.",
    hints: [
      "En Python, un certain type de collection supprime automatiquement les doublons.",
      "set() supprime les doublons. len(set(langages)) donne le nombre d'éléments différents.",
      "print(len(set(langages)))",
    ],
    hints_en: [
      "In Python, a certain type of collection automatically removes duplicates.",
      "set() removes duplicates. len(set(languages)) gives the number of different elements.",
      "print(len(set(languages)))",
    ],
    expectedOutput: "3",
    solutionCode: "langages = [\"python\", \"java\", \"python\", \"c++\", \"java\", \"python\"]\nprint(len(set(langages)))",
    solutionCode_en: 'languages = ["python", "java", "python", "c++", "java", "python"]\nprint(len(set(languages)))',
    minLevel: 2,
  },

  // ── MOYEN ────────────────────────────────────────────────────────────
  {
    id: "multiplication",
    emoji: "✖️",
    title: "Table de 7",
    title_en: "Times table of 7",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Affiche la table de multiplication de 7, de 7×1 jusqu'à 7×10.\nUn résultat par ligne.",
    description_en: "Display the multiplication table of 7, from 7×1 to 7×10.\nOne result per line.",
    starterCode: "# Affiche 7, 14, 21, ..., 70\n",
    starterCode_en: "# Display 7, 14, 21, ..., 70\n",
    hint: "Utilise une boucle for avec range(1, 11) et print(7 * i).",
    hint_en: "Use a for loop with range(1, 11) and print(7 * i).",
    hints: [
      "Tu dois répéter une opération 10 fois avec un compteur qui augmente.",
      "Utilise une boucle for avec range(1, 11) et print(7 * i).",
      "for i in range(1, 11):\n    print(7 * i)",
    ],
    hints_en: [
      "You need to repeat an operation 10 times with an increasing counter.",
      "Use a for loop with range(1, 11) and print(7 * i).",
      "for i in range(1, 11):\n    print(7 * i)",
    ],
    expectedOutput: "7\n14\n21\n28\n35\n42\n49\n56\n63\n70",
    solutionCode: "for i in range(1, 11):\n    print(7 * i)",
    minLevel: 1,
  },
  {
    id: "triangle",
    emoji: "🔺",
    title: "Triangle d'étoiles",
    title_en: "Star triangle",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Affiche un triangle de 5 lignes d'étoiles :\n*\n**\n***\n****\n*****",
    description_en: "Display a triangle of 5 rows of stars:\n*\n**\n***\n****\n*****",
    starterCode: "# Affiche un triangle de 5 lignes\n",
    starterCode_en: "# Display a triangle of 5 rows\n",
    hint: "Utilise une boucle for avec range(1, 6) et print('*' * i).",
    hint_en: "Use a for loop with range(1, 6) and print('*' * i).",
    hints: [
      "Chaque ligne contient un nombre d'étoiles égal à son numéro de ligne.",
      "Utilise une boucle for avec range(1, 6) et print('*' * i).",
      "for i in range(1, 6):\n    print('*' * i)",
    ],
    hints_en: [
      "Each row contains a number of stars equal to its row number.",
      "Use a for loop with range(1, 6) and print('*' * i).",
      "for i in range(1, 6):\n    print('*' * i)",
    ],
    expectedOutput: "*\n**\n***\n****\n*****",
    solutionCode: "for i in range(1, 6):\n    print(\"*\" * i)",
    minLevel: 1,
  },
  {
    id: "max",
    emoji: "🏆",
    title: "Le plus grand",
    title_en: "The largest",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Trouve le plus grand nombre dans cette liste et affiche-le :\n[34, 17, 89, 45, 12, 67]",
    description_en: "Find the largest number in this list and display it:\n[34, 17, 89, 45, 12, 67]",
    starterCode: "nombres = [34, 17, 89, 45, 12, 67]\n# Affiche le plus grand nombre\n",
    starterCode_en: "numbers = [34, 17, 89, 45, 12, 67]\n# Display the largest number\n",
    hint: "Utilise la fonction max() de Python.",
    hint_en: "Use Python's max() function.",
    hints: [
      "Python a une fonction intégrée pour trouver le plus grand élément d'une liste.",
      "Utilise la fonction max() de Python.",
      "print(max(nombres))",
    ],
    hints_en: [
      "Python has a built-in function to find the largest element in a list.",
      "Use Python's max() function.",
      "print(max(numbers))",
    ],
    expectedOutput: "89",
    solutionCode: "nombres = [34, 17, 89, 45, 12, 67]\nprint(max(nombres))",
    solutionCode_en: "numbers = [34, 17, 89, 45, 12, 67]\nprint(max(numbers))",
    minLevel: 2,
  },
  {
    id: "reverse",
    emoji: "🔄",
    title: "À l'envers",
    title_en: "Backwards",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Affiche le mot 'Python' écrit à l'envers.",
    description_en: "Display the word 'Python' written backwards.",
    starterCode: 'mot = "Python"\n# Affiche le mot à l\'envers\n',
    starterCode_en: 'word = "Python"\n# Display the word backwards\n',
    hint: "En Python, tu peux inverser une chaîne avec mot[::-1].",
    hint_en: "In Python, you can reverse a string with word[::-1].",
    hints: [
      "Python permet d'accéder aux éléments d'une séquence en sens inverse avec un pas négatif.",
      "En Python, tu peux inverser une chaîne avec mot[::-1].",
      "print(mot[::-1])",
    ],
    hints_en: [
      "Python lets you access elements of a sequence in reverse with a negative step.",
      "In Python, you can reverse a string with word[::-1].",
      "print(word[::-1])",
    ],
    expectedOutput: "nohtyP",
    solutionCode: "mot = \"Python\"\nprint(mot[::-1])",
    solutionCode_en: 'word = "Python"\nprint(word[::-1])',
    minLevel: 2,
  },
  {
    id: "palindrome",
    emoji: "🔁",
    title: "Palindrome",
    title_en: "Palindrome",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Un palindrome se lit pareil dans les deux sens (ex : 'kayak', 'radar').\nAffiche 'oui' si 'radar' est un palindrome, sinon 'non'.",
    description_en: "A palindrome reads the same in both directions (e.g. 'kayak', 'radar').\nDisplay 'yes' if 'radar' is a palindrome, 'no' otherwise.",
    starterCode: "mot = \"radar\"\n# Vérifie si c'est un palindrome\n",
    starterCode_en: "word = \"radar\"\n# Check if it's a palindrome\n",
    hint: "Compare mot avec mot[::-1] qui donne le mot à l'envers.",
    hint_en: "Compare word with word[::-1] which gives the word backwards.",
    hints: [
      "Comment vérifier qu'un mot est identique quand on le lit à l'envers ?",
      "Compare mot avec mot[::-1] qui donne le mot à l'envers.",
      'if mot == mot[::-1]:\n    print("oui")\nelse:\n    print("non")',
    ],
    hints_en: [
      "How can you check that a word is the same when read backwards?",
      "Compare word with word[::-1] which gives the word backwards.",
      'if word == word[::-1]:\n    print("yes")\nelse:\n    print("no")',
    ],
    expectedOutput: "oui",
    expectedOutput_en: "yes",
    solutionCode: "mot = \"radar\"\nif mot == mot[::-1]:\n    print(\"oui\")\nelse:\n    print(\"non\")",
    solutionCode_en: 'word = "radar"\nif word == word[::-1]:\n    print("yes")\nelse:\n    print("no")',
    minLevel: 2,
  },
  {
    id: "factorial",
    emoji: "❗",
    title: "Factorielle",
    title_en: "Factorial",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Calcule la factorielle de 6 et affiche le résultat.\n6! = 6 × 5 × 4 × 3 × 2 × 1",
    description_en: "Calculate the factorial of 6 and display the result.\n6! = 6 × 5 × 4 × 3 × 2 × 1",
    starterCode: "n = 6\n# Calcule n!\n",
    starterCode_en: "n = 6\n# Calculate n!\n",
    hint: "Commence avec result = 1, puis multiplie par chaque nombre de 1 à n.",
    hint_en: "Start with result = 1, then multiply by each number from 1 to n.",
    hints: [
      "Commence avec 1 et multiplie successivement par 2, 3, 4, 5, 6.",
      "Commence avec result = 1, puis multiplie par chaque nombre de 1 à n.",
      "result = 1\nfor i in range(1, n + 1):\n    result *= i\nprint(result)",
    ],
    hints_en: [
      "Start with 1 and multiply successively by 2, 3, 4, 5, 6.",
      "Start with result = 1, then multiply by each number from 1 to n.",
      "result = 1\nfor i in range(1, n + 1):\n    result *= i\nprint(result)",
    ],
    expectedOutput: "720",
    solutionCode: "n = 6\nresult = 1\nfor i in range(1, n + 1):\n    result *= i\nprint(result)",
    minLevel: 2,
  },
  {
    id: "sort_by_length",
    emoji: "📏",
    title: "Tri par longueur",
    title_en: "Sort by length",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Trie cette liste de mots du plus court au plus long et affiche-la.",
    description_en: "Sort this list of words from shortest to longest and display it.",
    starterCode: 'mots = ["chat", "elephant", "rat", "girafe", "pie"]\n# Trie par longueur et affiche\n',
    starterCode_en: 'words = ["chat", "elephant", "rat", "girafe", "pie"]\n# Sort by length and display\n',
    hint: "Utilise sorted(mots, key=len) pour trier par longueur.",
    hint_en: "Use sorted(words, key=len) to sort by length.",
    hints: [
      "La fonction sorted() peut trier selon un critère personnalisé avec key=.",
      "Utilise sorted(mots, key=len) pour trier par longueur.",
      "print(sorted(mots, key=len))",
    ],
    hints_en: [
      "The sorted() function can sort according to a custom criterion with key=.",
      "Use sorted(words, key=len) to sort by length.",
      "print(sorted(words, key=len))",
    ],
    expectedOutput: "['rat', 'pie', 'chat', 'girafe', 'elephant']",
    solutionCode: "mots = [\"chat\", \"elephant\", \"rat\", \"girafe\", \"pie\"]\nprint(sorted(mots, key=len))",
    solutionCode_en: 'words = ["chat", "elephant", "rat", "girafe", "pie"]\nprint(sorted(words, key=len))',
    minLevel: 2,
  },
  {
    id: "list_comp",
    emoji: "⚡",
    title: "Les carrés parfaits",
    title_en: "Perfect squares",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Crée la liste des carrés des nombres de 1 à 5 en une seule ligne et affiche-la.\n(1², 2², 3², 4², 5²)",
    description_en: "Create the list of squares of numbers from 1 to 5 in a single line and display it.\n(1², 2², 3², 4², 5²)",
    starterCode: "# Crée [1, 4, 9, 16, 25] en une ligne\n",
    starterCode_en: "# Create [1, 4, 9, 16, 25] in one line\n",
    hint: "Utilise [n**2 for n in range(1, 6)] pour créer la liste en une seule ligne.",
    hint_en: "Use [n**2 for n in range(1, 6)] to create the list in one line.",
    hints: [
      "En Python, tu peux créer une liste en une seule ligne avec [ ... for ... in ... ].",
      "Utilise [n**2 for n in range(1, 6)] pour créer la liste en une seule ligne.",
      "print([n**2 for n in range(1, 6)])",
    ],
    hints_en: [
      "In Python, you can create a list in one line with [ ... for ... in ... ].",
      "Use [n**2 for n in range(1, 6)] to create the list in one line.",
      "print([n**2 for n in range(1, 6)])",
    ],
    expectedOutput: "[1, 4, 9, 16, 25]",
    solutionCode: "print([n**2 for n in range(1, 6)])",
    minLevel: 2,
  },
  {
    id: "occurrences",
    emoji: "📊",
    title: "Compte les fruits",
    title_en: "Count the fruits",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Compte combien de fois chaque fruit apparaît et affiche le résultat.\nFormat attendu :\npomme: 3\nbanane: 2\ncerise: 1",
    description_en: "Count how many times each fruit appears and display the result.\nExpected format:\napple: 3\nbanana: 2\ncherry: 1",
    starterCode: 'fruits = ["pomme", "banane", "pomme", "cerise", "banane", "pomme"]\n# Compte les occurrences\n',
    starterCode_en: 'fruits = ["apple", "banana", "apple", "cherry", "banana", "apple"]\n# Count occurrences\n',
    hint: "Crée un dictionnaire vide {} et une boucle for. Pour chaque fruit, ajoute 1 à son compteur.",
    hint_en: "Create an empty dictionary {} and a for loop. For each fruit, add 1 to its counter.",
    hints: [
      "Tu as besoin d'une structure qui mémorise combien de fois chaque fruit apparaît.",
      "Crée un dictionnaire vide {} et une boucle for. Pour chaque fruit, ajoute 1 à son compteur.",
      "compte = {}\nfor f in fruits:\n    compte[f] = compte.get(f, 0) + 1\nfor fruit, n in compte.items():\n    print(f'{fruit}: {n}')",
    ],
    hints_en: [
      "You need a structure that remembers how many times each fruit appears.",
      "Create an empty dictionary {} and a for loop. For each fruit, add 1 to its counter.",
      "count = {}\nfor f in fruits:\n    count[f] = count.get(f, 0) + 1\nfor fruit, n in count.items():\n    print(f'{fruit}: {n}')",
    ],
    expectedOutput: "pomme: 3\nbanane: 2\ncerise: 1",
    expectedOutput_en: "apple: 3\nbanana: 2\ncherry: 1",
    solutionCode: "fruits = [\"pomme\", \"banane\", \"pomme\", \"cerise\", \"banane\", \"pomme\"]\ncompte = {}\nfor f in fruits:\n    compte[f] = compte.get(f, 0) + 1\nfor fruit, n in compte.items():\n    print(f\"{fruit}: {n}\")",
    solutionCode_en: 'fruits = ["apple", "banana", "apple", "cherry", "banana", "apple"]\ncount = {}\nfor f in fruits:\n    count[f] = count.get(f, 0) + 1\nfor fruit, n in count.items():\n    print(f"{fruit}: {n}")',
    minLevel: 3,
  },
  {
    id: "safe_divide",
    emoji: "🛡️",
    title: "Division sécurisée",
    title_en: "Safe division",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Écris une fonction divise(a, b) qui divise a par b.\nSi b vaut 0, affiche un message d'erreur au lieu de planter.\nAffiche divise(10, 2) puis divise(10, 0).",
    description_en: "Write a function divide(a, b) that divides a by b.\nIf b is 0, display an error message instead of crashing.\nDisplay divide(10, 2) then divide(10, 0).",
    starterCode: "def divise(a, b):\n    # Utilise try/except pour gérer la division par zéro\n    pass\n\nprint(divise(10, 2))\nprint(divise(10, 0))\n",
    starterCode_en: "def divide(a, b):\n    # Use try/except to handle division by zero\n    pass\n\nprint(divide(10, 2))\nprint(divide(10, 0))\n",
    hint: "Dans un bloc try, fais a // b. Dans except ZeroDivisionError, retourne le message d'erreur.",
    hint_en: "In a try block, do a // b. In except ZeroDivisionError, return the error message.",
    hints: [
      "Python peut attraper les erreurs avec un mécanisme spécial pour les gérer proprement.",
      "Dans un bloc try, fais a // b. Dans except ZeroDivisionError, retourne le message d'erreur.",
      "try:\n    return a // b\nexcept ZeroDivisionError:\n    return \"Erreur : division par zero !\"",
    ],
    hints_en: [
      "Python can catch errors with a special mechanism to handle them cleanly.",
      "In a try block, do a // b. In except ZeroDivisionError, return the error message.",
      "try:\n    return a // b\nexcept ZeroDivisionError:\n    return \"Error: division by zero!\"",
    ],
    expectedOutput: "5\nErreur : division par zero !",
    expectedOutput_en: "5\nError: division by zero!",
    solutionCode: "def divise(a, b):\n    try:\n        return a // b\n    except ZeroDivisionError:\n        return \"Erreur : division par zero !\"\n\nprint(divise(10, 2))\nprint(divise(10, 0))",
    solutionCode_en: 'def divide(a, b):\n    try:\n        return a // b\n    except ZeroDivisionError:\n        return "Error: division by zero!"\n\nprint(divide(10, 2))\nprint(divide(10, 0))',
    minLevel: 3,
  },

  // ── FACILE (suite) ────────────────────────────────────────────────────
  {
    id: "repeat_string",
    emoji: "🔁",
    title: "Répétition de texte",
    title_en: "Text repetition",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Affiche la chaîne 'Ha' répétée 5 fois d'affilée sans espace.\nRésultat attendu : HaHaHaHaHa",
    description_en: "Display the string 'Ha' repeated 5 times with no spaces.\nExpected result: HaHaHaHaHa",
    starterCode: '# Affiche "Ha" répété 5 fois\n',
    starterCode_en: '# Display "Ha" repeated 5 times\n',
    hint: "En Python, tu peux multiplier une chaîne avec * : \"Ha\" * 5.",
    hint_en: 'In Python, you can multiply a string with *: "Ha" * 5.',
    hints: [
      "En Python, l'opérateur * peut aussi s'appliquer aux chaînes de caractères.",
      "Tu peux multiplier une chaîne par un entier : \"texte\" * n.",
      'print("Ha" * 5)',
    ],
    hints_en: [
      "In Python, the * operator can also be applied to strings.",
      'You can multiply a string by an integer: "text" * n.',
      'print("Ha" * 5)',
    ],
    expectedOutput: "HaHaHaHaHa",
    solutionCode: 'print("Ha" * 5)',
    minLevel: 0,
  },
  {
    id: "abs_value",
    emoji: "📏",
    title: "Valeur absolue",
    title_en: "Absolute value",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Affiche la valeur absolue de -42.\nLa valeur absolue ignore le signe négatif.",
    description_en: "Display the absolute value of -42.\nAbsolute value ignores the negative sign.",
    starterCode: "n = -42\n# Affiche la valeur absolue\n",
    starterCode_en: "n = -42\n# Display the absolute value\n",
    hint: "Python a une fonction intégrée abs() pour la valeur absolue.",
    hint_en: "Python has a built-in abs() function for absolute value.",
    hints: [
      "Il existe une fonction Python qui retourne toujours un nombre positif.",
      "Python a une fonction intégrée abs() pour la valeur absolue.",
      "print(abs(n))",
    ],
    hints_en: [
      "There's a Python function that always returns a positive number.",
      "Python has a built-in abs() function for absolute value.",
      "print(abs(n))",
    ],
    expectedOutput: "42",
    solutionCode: "n = -42\nprint(abs(n))",
    minLevel: 0,
  },
  {
    id: "join_words",
    emoji: "🔗",
    title: "Réunis les mots",
    title_en: "Join the words",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Joins les mots de la liste avec un tiret entre chaque mot.\nRésultat attendu : Python-est-super",
    description_en: "Join the words in the list with a hyphen between each word.\nExpected result: Python-est-super",
    starterCode: 'mots = ["Python", "est", "super"]\n# Joins avec des tirets\n',
    starterCode_en: 'words = ["Python", "est", "super"]\n# Join with hyphens\n',
    hint: "Utilise la méthode join() : \"-\".join(mots).",
    hint_en: 'Use the join() method: "-".join(words).',
    hints: [
      "Il existe une méthode qui assemble des éléments d'une liste en une seule chaîne.",
      "Utilise la méthode join() : séparateur.join(liste).",
      'print("-".join(mots))',
    ],
    hints_en: [
      "There's a method that assembles list elements into a single string.",
      "Use the join() method: separator.join(list).",
      'print("-".join(words))',
    ],
    expectedOutput: "Python-est-super",
    solutionCode: 'mots = ["Python", "est", "super"]\nprint("-".join(mots))',
    solutionCode_en: 'words = ["Python", "est", "super"]\nprint("-".join(words))',
    minLevel: 1,
  },

  // ── MOYEN (suite) ─────────────────────────────────────────────────────
  {
    id: "dict_squares",
    emoji: "📐",
    title: "Dictionnaire des carrés",
    title_en: "Dictionary of squares",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Crée un dictionnaire où la clé est un nombre (1 à 4) et la valeur est son carré.\nAffiche-le.\nRésultat : {1: 1, 2: 4, 3: 9, 4: 16}",
    description_en: "Create a dictionary where the key is a number (1 to 4) and the value is its square.\nDisplay it.\nResult: {1: 1, 2: 4, 3: 9, 4: 16}",
    starterCode: "# Crée le dictionnaire des carrés\n",
    starterCode_en: "# Create the squares dictionary\n",
    hint: "Utilise {n: n**2 for n in range(1, 5)} pour créer le dictionnaire en une ligne.",
    hint_en: "Use {n: n**2 for n in range(1, 5)} to create the dictionary in one line.",
    hints: [
      "Tu peux créer un dictionnaire en une ligne avec { clé: valeur for ... in ... }.",
      "Utilise {n: n**2 for n in range(1, 5)} pour créer le dictionnaire en une ligne.",
      "print({n: n**2 for n in range(1, 5)})",
    ],
    hints_en: [
      "You can create a dictionary in one line with { key: value for ... in ... }.",
      "Use {n: n**2 for n in range(1, 5)} to create the dictionary in one line.",
      "print({n: n**2 for n in range(1, 5)})",
    ],
    expectedOutput: "{1: 1, 2: 4, 3: 9, 4: 16}",
    solutionCode: "print({n: n**2 for n in range(1, 5)})",
    minLevel: 3,
  },
  {
    id: "filter_evens",
    emoji: "🎰",
    title: "Filtre les pairs",
    title_en: "Filter the evens",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Garde uniquement les nombres pairs de la liste et affiche-les.\nRésultat attendu : [2, 4, 6, 8, 10]",
    description_en: "Keep only the even numbers from the list and display them.\nExpected result: [2, 4, 6, 8, 10]",
    starterCode: "nombres = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n# Garde uniquement les pairs\n",
    starterCode_en: "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n# Keep only the even ones\n",
    hint: "Utilise [n for n in nombres if n % 2 == 0].",
    hint_en: "Use [n for n in numbers if n % 2 == 0].",
    hints: [
      "Tu peux filtrer une liste avec une condition dans une compréhension de liste.",
      "Utilise [n for n in nombres if n % 2 == 0].",
      "print([n for n in nombres if n % 2 == 0])",
    ],
    hints_en: [
      "You can filter a list with a condition in a list comprehension.",
      "Use [n for n in numbers if n % 2 == 0].",
      "print([n for n in numbers if n % 2 == 0])",
    ],
    expectedOutput: "[2, 4, 6, 8, 10]",
    solutionCode: "nombres = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\nprint([n for n in nombres if n % 2 == 0])",
    solutionCode_en: "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\nprint([n for n in numbers if n % 2 == 0])",
    minLevel: 2,
  },

  // ── DIFFICILE ────────────────────────────────────────────────────────
  {
    id: "fizzbuzz",
    emoji: "🎯",
    title: "FizzBuzz",
    title_en: "FizzBuzz",
    difficulty: "Difficile",
    difficultyColor: "from-pink-500 to-rose-600",
    description: "Affiche les nombres de 1 à 15, mais :\n→ Si divisible par 3 : affiche 'Fizz'\n→ Si divisible par 5 : affiche 'Buzz'\n→ Si divisible par 3 ET 5 : affiche 'FizzBuzz'\n→ Sinon : affiche le nombre",
    description_en: "Display numbers from 1 to 15, but:\n→ If divisible by 3: display 'Fizz'\n→ If divisible by 5: display 'Buzz'\n→ If divisible by 3 AND 5: display 'FizzBuzz'\n→ Otherwise: display the number",
    starterCode: "# FizzBuzz de 1 à 15\n",
    starterCode_en: "# FizzBuzz from 1 to 15\n",
    hint: "Vérifie d'abord si divisible par 15 (FizzBuzz), puis par 3, puis par 5.",
    hint_en: "Check first if divisible by 15 (FizzBuzz), then by 3, then by 5.",
    hints: [
      "Teste les divisibilités dans le bon ordre — commence par le cas le plus spécifique.",
      "Vérifie d'abord si divisible par 15 (FizzBuzz), puis par 3, puis par 5.",
      "for i in range(1, 16):\n    if i % 15 == 0: print('FizzBuzz')\n    elif i % 3 == 0: print('Fizz')\n    elif i % 5 == 0: print('Buzz')\n    else: print(i)",
    ],
    hints_en: [
      "Test divisibility in the right order — start with the most specific case.",
      "Check first if divisible by 15 (FizzBuzz), then by 3, then by 5.",
      "for i in range(1, 16):\n    if i % 15 == 0: print('FizzBuzz')\n    elif i % 3 == 0: print('Fizz')\n    elif i % 5 == 0: print('Buzz')\n    else: print(i)",
    ],
    expectedOutput: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz",
    solutionCode: "for i in range(1, 16):\n    if i % 15 == 0:\n        print(\"FizzBuzz\")\n    elif i % 3 == 0:\n        print(\"Fizz\")\n    elif i % 5 == 0:\n        print(\"Buzz\")\n    else:\n        print(i)",
    minLevel: 2,
  },
  {
    id: "fibonacci",
    emoji: "🌀",
    title: "Suite de Fibonacci",
    title_en: "Fibonacci sequence",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Affiche les 8 premiers nombres de la suite de Fibonacci, séparés par des virgules.\nChaque nombre est la somme des deux précédents :\n0, 1, 1, 2, 3, 5, 8, 13…",
    description_en: "Display the first 8 numbers of the Fibonacci sequence, separated by commas.\nEach number is the sum of the two previous ones:\n0, 1, 1, 2, 3, 5, 8, 13…",
    starterCode: "# Affiche : 0, 1, 1, 2, 3, 5, 8, 13\n",
    starterCode_en: "# Display: 0, 1, 1, 2, 3, 5, 8, 13\n",
    hint: "Commence avec a=0, b=1. À chaque étape, fais : a, b = b, a+b.",
    hint_en: "Start with a=0, b=1. At each step: a, b = b, a+b.",
    hints: [
      "Garde en mémoire les deux derniers nombres de la suite pour calculer le suivant.",
      "Commence avec a=0, b=1. À chaque étape, fais : a, b = b, a+b.",
      "a, b = 0, 1\nres = []\nfor _ in range(8):\n    res.append(str(a))\n    a, b = b, a + b\nprint(', '.join(res))",
    ],
    hints_en: [
      "Keep track of the last two numbers in the sequence to calculate the next.",
      "Start with a=0, b=1. At each step: a, b = b, a+b.",
      "a, b = 0, 1\nres = []\nfor _ in range(8):\n    res.append(str(a))\n    a, b = b, a + b\nprint(', '.join(res))",
    ],
    expectedOutput: "0, 1, 1, 2, 3, 5, 8, 13",
    solutionCode: "a, b = 0, 1\nresultat = []\nfor _ in range(8):\n    resultat.append(str(a))\n    a, b = b, a + b\nprint(\", \".join(resultat))",
    minLevel: 3,
  },
  {
    id: "primes",
    emoji: "🔢",
    title: "Nombres premiers",
    title_en: "Prime numbers",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Affiche tous les nombres premiers entre 2 et 20, séparés par des virgules.\nUn nombre premier n'est divisible que par 1 et lui-même.",
    description_en: "Display all prime numbers between 2 and 20, separated by commas.\nA prime number is only divisible by 1 and itself.",
    starterCode: "# Affiche les nombres premiers de 2 à 20\n",
    starterCode_en: "# Display prime numbers from 2 to 20\n",
    hint: "Pour chaque nombre n, vérifie qu'aucun entier entre 2 et n-1 ne le divise.",
    hint_en: "For each number n, check that no integer between 2 and n-1 divides it.",
    hints: [
      "Pour chaque nombre, vérifie qu'aucun entier entre 2 et lui-même ne peut le diviser.",
      "Pour chaque nombre n, vérifie qu'aucun entier entre 2 et n-1 ne le divise.",
      "premiers = []\nfor n in range(2, 21):\n    if all(n % i != 0 for i in range(2, n)):\n        premiers.append(str(n))\nprint(', '.join(premiers))",
    ],
    hints_en: [
      "For each number, check that no integer between 2 and itself can divide it.",
      "For each number n, check that no integer between 2 and n-1 divides it.",
      "primes = []\nfor n in range(2, 21):\n    if all(n % i != 0 for i in range(2, n)):\n        primes.append(str(n))\nprint(', '.join(primes))",
    ],
    expectedOutput: "2, 3, 5, 7, 11, 13, 17, 19",
    solutionCode: "premiers = []\nfor n in range(2, 21):\n    if all(n % i != 0 for i in range(2, n)):\n        premiers.append(str(n))\nprint(\", \".join(premiers))",
    solutionCode_en: "primes = []\nfor n in range(2, 21):\n    if all(n % i != 0 for i in range(2, n)):\n        primes.append(str(n))\nprint(\", \".join(primes))",
    minLevel: 3,
  },
  {
    id: "class_animal",
    emoji: "🐕",
    title: "Ma première classe",
    title_en: "My first class",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Crée une classe Animal avec :\n- un attribut nom\n- une méthode parler() qui retourne \"<nom> dit Bonjour !\"\n\nCrée un Animal nommé 'Rex' et affiche parler().",
    description_en: "Create a class Animal with:\n- a name attribute\n- a speak() method that returns \"<name> says Hello!\"\n\nCreate an Animal named 'Rex' and display speak().",
    starterCode: "# Crée la classe Animal\n\n\n# Crée un Animal nommé Rex et affiche parler()\n",
    starterCode_en: "# Create the Animal class\n\n\n# Create an Animal named Rex and display speak()\n",
    hint: "Dans __init__(self, nom), stocke self.nom = nom. Dans parler(self), retourne f\"{self.nom} dit Bonjour !\"",
    hint_en: 'In __init__(self, name), store self.name = name. In speak(self), return f"{self.name} says Hello!"',
    hints: [
      "En Python, une classe se définit avec class, et son constructeur s'appelle __init__.",
      "Dans __init__(self, nom), stocke self.nom = nom. Dans parler(self), retourne f\"{self.nom} dit Bonjour !\"",
      "class Animal:\n    def __init__(self, nom):\n        self.nom = nom\n    def parler(self):\n        return f\"{self.nom} dit Bonjour !\"",
    ],
    hints_en: [
      "In Python, a class is defined with class, and its constructor is called __init__.",
      'In __init__(self, name), store self.name = name. In speak(self), return f"{self.name} says Hello!"',
      "class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return f\"{self.name} says Hello!\"",
    ],
    expectedOutput: "Rex dit Bonjour !",
    expectedOutput_en: "Rex says Hello!",
    solutionCode: "class Animal:\n    def __init__(self, nom):\n        self.nom = nom\n    def parler(self):\n        return f\"{self.nom} dit Bonjour !\"\n\nrex = Animal(\"Rex\")\nprint(rex.parler())",
    solutionCode_en: 'class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return f"{self.name} says Hello!"\n\nrex = Animal("Rex")\nprint(rex.speak())',
    minLevel: 4,
  },
  {
    id: "two_sum",
    emoji: "🎯",
    title: "Deux nombres = 10",
    title_en: "Two numbers = 10",
    difficulty: "Difficile",
    difficultyColor: "from-pink-500 to-rose-600",
    description: "Trouve deux nombres dans la liste dont la somme vaut 10 et affiche leurs indices.\nFormat : 0 3\n(les indices du premier couple trouvé)",
    description_en: "Find two numbers in the list whose sum equals 10 and display their indices.\nFormat: 0 3\n(the indices of the first pair found)",
    starterCode: "nums = [2, 7, 4, 3, 6]\n# Affiche les deux indices dont la somme vaut 10\n",
    starterCode_en: "nums = [2, 7, 4, 3, 6]\n# Display the two indices whose sum equals 10\n",
    hint: "Parcours toutes les paires avec deux boucles imbriquées et vérifie si nums[i] + nums[j] == 10.",
    hint_en: "Loop through all pairs with two nested loops and check if nums[i] + nums[j] == 10.",
    hints: [
      "Tu as besoin de tester toutes les combinaisons de deux éléments différents.",
      "Parcours toutes les paires avec deux boucles imbriquées (for i et for j > i).",
      "for i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i] + nums[j] == 10:\n            print(i, j)",
    ],
    hints_en: [
      "You need to test all combinations of two different elements.",
      "Loop through all pairs with two nested loops (for i and for j > i).",
      "for i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i] + nums[j] == 10:\n            print(i, j)",
    ],
    expectedOutput: "0 3",
    solutionCode: "nums = [2, 7, 4, 3, 6]\nfor i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i] + nums[j] == 10:\n            print(i, j)\n            break",
    minLevel: 3,
  },
  {
    id: "flatten",
    emoji: "📋",
    title: "Aplatir une liste",
    title_en: "Flatten a list",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Transforme cette liste de listes en une seule liste plate et affiche-la.\nRésultat : [1, 2, 3, 4, 5, 6]",
    description_en: "Transform this list of lists into a single flat list and display it.\nResult: [1, 2, 3, 4, 5, 6]",
    starterCode: "matrice = [[1, 2], [3, 4], [5, 6]]\n# Crée une liste plate\n",
    starterCode_en: "matrix = [[1, 2], [3, 4], [5, 6]]\n# Create a flat list\n",
    hint: "Utilise [x for sous_liste in matrice for x in sous_liste].",
    hint_en: "Use [x for sublist in matrix for x in sublist].",
    hints: [
      "Tu as besoin d'une boucle qui parcourt chaque sous-liste et chaque élément.",
      "Avec une compréhension de liste à deux for : [x for sous in matrice for x in sous].",
      "print([x for sous_liste in matrice for x in sous_liste])",
    ],
    hints_en: [
      "You need a loop that goes through each sublist and each element.",
      "With a two-for list comprehension: [x for sub in matrix for x in sub].",
      "print([x for sublist in matrix for x in sublist])",
    ],
    expectedOutput: "[1, 2, 3, 4, 5, 6]",
    solutionCode: "matrice = [[1, 2], [3, 4], [5, 6]]\nprint([x for sous_liste in matrice for x in sous_liste])",
    solutionCode_en: "matrix = [[1, 2], [3, 4], [5, 6]]\nprint([x for sublist in matrix for x in sublist])",
    minLevel: 4,
  },
  {
    id: "bubble_sort",
    emoji: "🫧",
    title: "Tri à bulles",
    title_en: "Bubble sort",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Implémente le tri à bulles pour trier cette liste et affiche le résultat.\n[5, 3, 8, 1, 9, 2] → [1, 2, 3, 5, 8, 9]",
    description_en: "Implement bubble sort to sort this list and display the result.\n[5, 3, 8, 1, 9, 2] → [1, 2, 3, 5, 8, 9]",
    starterCode: "nums = [5, 3, 8, 1, 9, 2]\n# Trie avec le tri à bulles\n",
    starterCode_en: "nums = [5, 3, 8, 1, 9, 2]\n# Sort with bubble sort\n",
    hint: "Fais deux boucles imbriquées. Si nums[j] > nums[j+1], échange-les.",
    hint_en: "Use two nested loops. If nums[j] > nums[j+1], swap them.",
    hints: [
      "Le tri à bulles compare chaque paire adjacente et les échange si besoin, en répétant jusqu'à ce que la liste soit triée.",
      "Fais deux boucles imbriquées. Si nums[j] > nums[j+1], échange-les.",
      "for i in range(len(nums)):\n    for j in range(len(nums)-i-1):\n        if nums[j] > nums[j+1]:\n            nums[j], nums[j+1] = nums[j+1], nums[j]\nprint(nums)",
    ],
    hints_en: [
      "Bubble sort compares each adjacent pair and swaps them if needed, repeating until the list is sorted.",
      "Use two nested loops. If nums[j] > nums[j+1], swap them.",
      "for i in range(len(nums)):\n    for j in range(len(nums)-i-1):\n        if nums[j] > nums[j+1]:\n            nums[j], nums[j+1] = nums[j+1], nums[j]\nprint(nums)",
    ],
    expectedOutput: "[1, 2, 3, 5, 8, 9]",
    solutionCode: "nums = [5, 3, 8, 1, 9, 2]\nfor i in range(len(nums)):\n    for j in range(len(nums)-i-1):\n        if nums[j] > nums[j+1]:\n            nums[j], nums[j+1] = nums[j+1], nums[j]\nprint(nums)",
    minLevel: 4,
  },
  {
    id: "power_recursive",
    emoji: "🔁",
    title: "Puissance récursive",
    title_en: "Recursive power",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Écris une fonction récursive puissance(base, exp) qui calcule base^exp.\nUne fonction récursive s'appelle elle-même !\nAffiche puissance(2, 8).",
    description_en: "Write a recursive function power(base, exp) that calculates base^exp.\nA recursive function calls itself!\nDisplay power(2, 8).",
    starterCode: "def puissance(base, exp):\n    # Si exp vaut 0, retourne 1\n    # Sinon retourne base * puissance(base, exp - 1)\n    pass\n\nprint(puissance(2, 8))\n",
    starterCode_en: "def power(base, exp):\n    # If exp is 0, return 1\n    # Otherwise return base * power(base, exp - 1)\n    pass\n\nprint(power(2, 8))\n",
    hint: "Si exp == 0, retourne 1. Sinon retourne base * puissance(base, exp - 1).",
    hint_en: "If exp == 0, return 1. Otherwise return base * power(base, exp - 1).",
    hints: [
      "Une fonction récursive s'appelle elle-même avec une valeur plus petite, jusqu'à un cas de base.",
      "Si exp == 0, retourne 1. Sinon retourne base * puissance(base, exp - 1).",
      "def puissance(base, exp):\n    if exp == 0:\n        return 1\n    return base * puissance(base, exp - 1)",
    ],
    hints_en: [
      "A recursive function calls itself with a smaller value, down to a base case.",
      "If exp == 0, return 1. Otherwise return base * power(base, exp - 1).",
      "def power(base, exp):\n    if exp == 0:\n        return 1\n    return base * power(base, exp - 1)",
    ],
    expectedOutput: "256",
    solutionCode: "def puissance(base, exp):\n    if exp == 0:\n        return 1\n    return base * puissance(base, exp - 1)\n\nprint(puissance(2, 8))",
    solutionCode_en: "def power(base, exp):\n    if exp == 0:\n        return 1\n    return base * power(base, exp - 1)\n\nprint(power(2, 8))",
    minLevel: 4,
  },

  // ── FACILE (extra) ────────────────────────────────────────────────────
  {
    id: "temperature",
    emoji: "🌡️",
    title: "Celsius en Fahrenheit",
    title_en: "Celsius to Fahrenheit",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Convertis 100 degrés Celsius en Fahrenheit et affiche le résultat.\nFormule : F = C × 9/5 + 32",
    description_en: "Convert 100 degrees Celsius to Fahrenheit and display the result.\nFormula: F = C × 9/5 + 32",
    starterCode: "celsius = 100\n# Calcule et affiche la valeur en Fahrenheit\n",
    starterCode_en: "celsius = 100\n# Calculate and display the Fahrenheit value\n",
    hint: "Applique la formule : fahrenheit = celsius * 9/5 + 32.",
    hint_en: "Apply the formula: fahrenheit = celsius * 9/5 + 32.",
    hints: [
      "Il existe une formule mathématique simple pour convertir Celsius en Fahrenheit.",
      "Applique la formule : fahrenheit = celsius * 9 / 5 + 32.",
      "fahrenheit = celsius * 9 / 5 + 32\nprint(fahrenheit)",
    ],
    hints_en: [
      "There's a simple mathematical formula to convert Celsius to Fahrenheit.",
      "Apply the formula: fahrenheit = celsius * 9 / 5 + 32.",
      "fahrenheit = celsius * 9 / 5 + 32\nprint(fahrenheit)",
    ],
    expectedOutput: "212.0",
    solutionCode: "celsius = 100\nfahrenheit = celsius * 9 / 5 + 32\nprint(fahrenheit)",
    minLevel: 0,
  },
  {
    id: "min_max",
    emoji: "📊",
    title: "Mini-stats",
    title_en: "Mini-stats",
    difficulty: "Facile",
    difficultyColor: "from-green-400 to-emerald-500",
    description: "Affiche le minimum, le maximum et la moyenne de cette liste.\nUne valeur par ligne.\nFormat :\nMin: 3\nMax: 95\nMoyenne: 42.0",
    description_en: "Display the minimum, maximum and average of this list.\nOne value per line.\nFormat:\nMin: 3\nMax: 95\nAverage: 47.71...",
    starterCode: "notes = [15, 3, 87, 42, 95, 68, 24]\n# Affiche min, max et moyenne\n",
    starterCode_en: "scores = [15, 3, 87, 42, 95, 68, 24]\n# Display min, max and average\n",
    hint: "Utilise min(), max() et sum()/len() pour la moyenne.",
    hint_en: "Use min(), max() and sum()/len() for the average.",
    hints: [
      "Python a des fonctions intégrées pour trouver le minimum et le maximum d'une liste.",
      "Utilise min(), max() et sum(notes)/len(notes) pour la moyenne.",
      "print(f'Min: {min(notes)}')\nprint(f'Max: {max(notes)}')\nprint(f'Moyenne: {sum(notes)/len(notes)}')",
    ],
    hints_en: [
      "Python has built-in functions to find the minimum and maximum of a list.",
      "Use min(), max() and sum(scores)/len(scores) for the average.",
      "print(f'Min: {min(scores)}')\nprint(f'Max: {max(scores)}')\nprint(f'Average: {sum(scores)/len(scores)}')",
    ],
    expectedOutput: "Min: 3\nMax: 95\nMoyenne: 47.71428571428571",
    expectedOutput_en: "Min: 3\nMax: 95\nAverage: 47.71428571428571",
    solutionCode: "notes = [15, 3, 87, 42, 95, 68, 24]\nprint(f'Min: {min(notes)}')\nprint(f'Max: {max(notes)}')\nprint(f'Moyenne: {sum(notes)/len(notes)}')",
    solutionCode_en: "scores = [15, 3, 87, 42, 95, 68, 24]\nprint(f'Min: {min(scores)}')\nprint(f'Max: {max(scores)}')\nprint(f'Average: {sum(scores)/len(scores)}')",
    minLevel: 1,
  },

  // ── MOYEN (extra) ─────────────────────────────────────────────────────
  {
    id: "anagram",
    emoji: "🔀",
    title: "Anagramme",
    title_en: "Anagram",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "'listen' et 'silent' sont-ils des anagrammes ?\nAffiche 'oui' si les deux mots ont exactement les mêmes lettres (dans n'importe quel ordre), sinon 'non'.",
    description_en: "Are 'listen' and 'silent' anagrams?\nDisplay 'yes' if the two words have exactly the same letters (in any order), 'no' otherwise.",
    starterCode: "a = \"listen\"\nb = \"silent\"\n# Vérifie si ce sont des anagrammes\n",
    hint: "Trie les lettres des deux mots et compare : sorted(a) == sorted(b).",
    hint_en: "Sort the letters of both words and compare: sorted(a) == sorted(b).",
    hints: [
      "Deux anagrammes ont les mêmes lettres — comment les rendre comparables ?",
      "Trie les lettres des deux mots et compare-les.",
      "if sorted(a) == sorted(b):\n    print('oui')\nelse:\n    print('non')",
    ],
    hints_en: [
      "Two anagrams have the same letters — how can you make them comparable?",
      "Sort the letters of both words and compare them.",
      "if sorted(a) == sorted(b):\n    print('yes')\nelse:\n    print('no')",
    ],
    expectedOutput: "oui",
    expectedOutput_en: "yes",
    solutionCode: "a = \"listen\"\nb = \"silent\"\nif sorted(a) == sorted(b):\n    print('oui')\nelse:\n    print('non')",
    solutionCode_en: "a = \"listen\"\nb = \"silent\"\nif sorted(a) == sorted(b):\n    print('yes')\nelse:\n    print('no')",
    minLevel: 2,
  },
  {
    id: "matrix_diag",
    emoji: "🔷",
    title: "Diagonale d'une matrice",
    title_en: "Matrix diagonal",
    difficulty: "Moyen",
    difficultyColor: "from-yellow-400 to-orange-400",
    description: "Affiche la somme des éléments de la diagonale principale de cette matrice 3×3.\nDiagonale : 1, 5, 9 → Somme : 15",
    description_en: "Display the sum of the elements of the main diagonal of this 3×3 matrix.\nDiagonal: 1, 5, 9 → Sum: 15",
    starterCode: "matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\n# Affiche la somme de la diagonale\n",
    starterCode_en: "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\n# Display the sum of the diagonal\n",
    hint: "Les éléments de la diagonale ont le même indice de ligne et de colonne : matrice[i][i].",
    hint_en: "The diagonal elements have the same row and column index: matrix[i][i].",
    hints: [
      "Pense aux indices : pour une matrice n×n, la diagonale est matrice[0][0], matrice[1][1], matrice[2][2]...",
      "Utilise sum(matrice[i][i] for i in range(len(matrice))).",
      "print(sum(matrice[i][i] for i in range(len(matrice))))",
    ],
    hints_en: [
      "Think about the indices: for an n×n matrix, the diagonal is matrix[0][0], matrix[1][1], matrix[2][2]...",
      "Use sum(matrix[i][i] for i in range(len(matrix))).",
      "print(sum(matrix[i][i] for i in range(len(matrix))))",
    ],
    expectedOutput: "15",
    solutionCode: "matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nprint(sum(matrice[i][i] for i in range(len(matrice))))",
    solutionCode_en: "matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nprint(sum(matrix[i][i] for i in range(len(matrix))))",
    minLevel: 3,
  },

  // ── DIFFICILE (extra) ─────────────────────────────────────────────────
  {
    id: "caesar_cipher",
    emoji: "🔐",
    title: "Chiffre de César",
    title_en: "Caesar cipher",
    difficulty: "Difficile",
    difficultyColor: "from-purple-500 to-violet-600",
    description: "Encode le message 'hello' avec le chiffre de César (décalage de 3).\nh→k, e→h, l→o, l→o, o→r\nRésultat attendu : khoor",
    description_en: "Encode the message 'hello' with the Caesar cipher (shift of 3).\nh→k, e→h, l→o, l→o, o→r\nExpected result: khoor",
    starterCode: "message = \"hello\"\ndecalage = 3\n# Encode le message\n",
    starterCode_en: 'message = "hello"\nshift = 3\n# Encode the message\n',
    hint: "Pour chaque lettre, utilise chr((ord(c) - ord('a') + decalage) % 26 + ord('a')).",
    hint_en: "For each letter, use chr((ord(c) - ord('a') + shift) % 26 + ord('a')).",
    hints: [
      "Tu dois décaler chaque lettre de 3 positions dans l'alphabet, en bouclant si besoin.",
      "ord() convertit un caractère en nombre, chr() fait l'inverse.",
      "result = ''\nfor c in message:\n    result += chr((ord(c) - ord('a') + decalage) % 26 + ord('a'))\nprint(result)",
    ],
    hints_en: [
      "You need to shift each letter 3 positions in the alphabet, wrapping around if needed.",
      "ord() converts a character to a number, chr() does the inverse.",
      "result = ''\nfor c in message:\n    result += chr((ord(c) - ord('a') + shift) % 26 + ord('a'))\nprint(result)",
    ],
    expectedOutput: "khoor",
    solutionCode: "message = \"hello\"\ndecalage = 3\nresult = \"\"\nfor c in message:\n    result += chr((ord(c) - ord(\"a\") + decalage) % 26 + ord(\"a\"))\nprint(result)",
    solutionCode_en: 'message = "hello"\nshift = 3\nresult = ""\nfor c in message:\n    result += chr((ord(c) - ord("a") + shift) % 26 + ord("a"))\nprint(result)',
    minLevel: 4,
  },
];

import { getProgress, saveProgress } from "./progress";
import { notifyProgress } from "./events";
import { postActivity } from "./activity";

const STORAGE_KEY = "pythonkids_challenges";

export function getCompletedChallenges(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

/** Marque le défi comme terminé et retourne les nouveaux badges gagnés. */
export function markChallengeComplete(id: string): string[] {
  const done = getCompletedChallenges();
  if (done.includes(id)) return [];

  const newDone = [...done, id];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(newDone));

  const newBadges: string[] = [];
  try {
    const progress = getProgress();
    if (!progress.earnedBadges.includes("challenge_master")) {
      newBadges.push("challenge_master");
    }
    if (newDone.length >= CHALLENGES.length && !progress.earnedBadges.includes("challenge_all")) {
      newBadges.push("challenge_all");
    }
    if (newBadges.length > 0) {
      saveProgress({ ...progress, earnedBadges: [...progress.earnedBadges, ...newBadges] });
    }
  } catch { /* ignore */ }

  notifyProgress();
  postActivity("challenge", id);
  for (const badge of newBadges) postActivity("badge", badge);
  return newBadges;
}
