export interface LevelMeta {
  id: number;
  emoji: string;
  name: string;
  name_en?: string;
  description: string;
  description_en?: string;
  ages: string;
  ages_en?: string;
  color: string;
  bg: string;
  darkBg: string;
  border: string;
  darkBorder: string;
  lessons: number;
}

export const LEVELS: LevelMeta[] = [
  {
    id: 0,
    emoji: "🌟",
    name: "Premiers pas",
    name_en: "First Steps",
    description: "Découvre la magie du code ! Fais parler l'ordinateur dès ta première leçon.",
    description_en: "Discover the magic of code! Make the computer talk in your very first lesson.",
    ages: "8-10 ans",
    ages_en: "Ages 8–10",
    color: "from-green-400 to-emerald-500",
    bg: "bg-green-50",
    darkBg: "dark:bg-green-950/30",
    border: "border-green-200",
    darkBorder: "dark:border-green-800",
    lessons: 4,
  },
  {
    id: 1,
    emoji: "⭐",
    name: "Débutant",
    name_en: "Beginner",
    description: "Variables, conditions, boucles et tes premières vraies interactions !",
    description_en: "Variables, conditions, loops and your first real interactions!",
    ages: "10-12 ans",
    ages_en: "Ages 10–12",
    color: "from-yellow-400 to-orange-400",
    bg: "bg-yellow-50",
    darkBg: "dark:bg-yellow-950/30",
    border: "border-yellow-200",
    darkBorder: "dark:border-yellow-800",
    lessons: 8,
  },
  {
    id: 2,
    emoji: "🚀",
    name: "Explorateur",
    name_en: "Explorer",
    description: "Boucles, listes, fonctions, tuples pour créer des programmes puissants.",
    description_en: "Loops, lists, functions, tuples — build powerful programs.",
    ages: "12-14 ans",
    ages_en: "Ages 12–14",
    color: "from-blue-400 to-cyan-500",
    bg: "bg-blue-50",
    darkBg: "dark:bg-blue-950/30",
    border: "border-blue-200",
    darkBorder: "dark:border-blue-800",
    lessons: 6,
  },
  {
    id: 3,
    emoji: "🔨",
    name: "Bâtisseur",
    name_en: "Builder",
    description: "Dictionnaires, sets, compréhensions et débogage comme un pro.",
    description_en: "Dictionaries, sets, comprehensions and debugging like a pro.",
    ages: "14-16 ans",
    ages_en: "Ages 14–16",
    color: "from-purple-500 to-violet-600",
    bg: "bg-purple-50",
    darkBg: "dark:bg-purple-950/30",
    border: "border-purple-200",
    darkBorder: "dark:border-purple-800",
    lessons: 6,
  },
  {
    id: 4,
    emoji: "🏆",
    name: "Expert",
    name_en: "Expert",
    description: "POO, récursivité, lambda, algorithmes — crée de vrais projets !",
    description_en: "OOP, recursion, lambda, algorithms — build real projects!",
    ages: "16-18 ans",
    ages_en: "Ages 16–18",
    color: "from-pink-500 to-rose-600",
    bg: "bg-pink-50",
    darkBg: "dark:bg-pink-950/30",
    border: "border-pink-200",
    darkBorder: "dark:border-pink-800",
    lessons: 6,
  },
  {
    id: 5,
    emoji: "🌐",
    name: "Maître",
    name_en: "Master",
    description: "JSON, regex, collections, sécurité — maîtrise le Python avancé !",
    description_en: "JSON, regex, collections, security — master advanced Python!",
    ages: "16-18 ans",
    ages_en: "Ages 16–18",
    color: "from-cyan-500 to-blue-600",
    bg: "bg-cyan-50",
    darkBg: "dark:bg-cyan-950/30",
    border: "border-cyan-200",
    darkBorder: "dark:border-cyan-800",
    lessons: 6,
  },
  {
    id: 6,
    emoji: "🏗️",
    name: "Architecte",
    name_en: "Architect",
    description: "Héritage, décorateurs, générateurs, dataclasses — structure ton code comme un pro !",
    description_en: "Inheritance, decorators, generators, dataclasses — structure your code like a pro!",
    ages: "16-18 ans",
    ages_en: "Ages 16–18",
    color: "from-violet-500 to-purple-700",
    bg: "bg-violet-50",
    darkBg: "dark:bg-violet-950/30",
    border: "border-violet-200",
    darkBorder: "dark:border-violet-800",
    lessons: 6,
  },
  {
    id: 7,
    emoji: "🔬",
    name: "Chercheur",
    name_en: "Researcher",
    description: "statistics, itertools, functools, CSV, algorithmes — analyse des données comme un scientifique !",
    description_en: "statistics, itertools, functools, CSV, algorithms — analyze data like a scientist!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-teal-500 to-cyan-600",
    bg: "bg-teal-50",
    darkBg: "dark:bg-teal-950/30",
    border: "border-teal-200",
    darkBorder: "dark:border-teal-800",
    lessons: 6,
  },
  {
    id: 8,
    emoji: "🛠️",
    name: "Ingénieur",
    name_en: "Engineer",
    description: "Tests unitaires, fichiers, exceptions sur-mesure, type hints — code comme un pro en entreprise !",
    description_en: "Unit tests, files, custom exceptions, type hints — code like a professional!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-orange-500 to-amber-500",
    bg: "bg-orange-50",
    darkBg: "dark:bg-orange-950/30",
    border: "border-orange-200",
    darkBorder: "dark:border-orange-800",
    lessons: 6,
  },
  {
    id: 9,
    emoji: "🌟",
    name: "Pionnier",
    name_en: "Pioneer",
    description: "Design patterns, classes abstraites, métaclasses, programmation fonctionnelle — le sommet de Python !",
    description_en: "Design patterns, abstract classes, metaclasses, functional programming — the peak of Python!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-50",
    darkBg: "dark:bg-rose-950/30",
    border: "border-rose-200",
    darkBorder: "dark:border-rose-800",
    lessons: 6,
  },
  {
    id: 10,
    emoji: "⚒️",
    name: "Maître Artisan",
    name_en: "Master Craftsman",
    description: "enum, SQLite3, logging, surcharge d'opérateurs, descripteurs — outils puissants du Python pro !",
    description_en: "enum, SQLite3, logging, operator overloading, descriptors — powerful tools of the Python pro!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-lime-500 to-green-600",
    bg: "bg-lime-50",
    darkBg: "dark:bg-lime-950/30",
    border: "border-lime-200",
    darkBorder: "dark:border-lime-800",
    lessons: 6,
  },
  {
    id: 11,
    emoji: "👑",
    name: "Grand Maître",
    name_en: "Grand Master",
    description: "TypeVar, Generic, Protocol, __slots__, regex avancé — maîtrise absolue du Python !",
    description_en: "TypeVar, Generic, Protocol, __slots__, advanced regex — absolute mastery of Python!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-yellow-400 to-amber-500",
    bg: "bg-yellow-50",
    darkBg: "dark:bg-yellow-950/30",
    border: "border-yellow-200",
    darkBorder: "dark:border-yellow-800",
    lessons: 6,
  },
  {
    id: 12,
    emoji: "🌐",
    name: "Data & APIs",
    name_en: "Data & APIs",
    description: "JSON, CSV, collections avancées, statistics, tri optimisé — traite et analyse des données réelles !",
    description_en: "JSON, CSV, advanced collections, statistics, optimized sorting — process and analyze real data!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-sky-500 to-indigo-600",
    bg: "bg-sky-50",
    darkBg: "dark:bg-sky-950/30",
    border: "border-sky-200",
    darkBorder: "dark:border-sky-800",
    lessons: 6,
  },
  {
    id: 13,
    emoji: "🧮",
    name: "Algorithmiste",
    name_en: "Algorithmist",
    description: "Graphes, BFS/DFS, programmation dynamique, arbres binaires, Dijkstra — résous des problèmes complexes !",
    description_en: "Graphs, BFS/DFS, dynamic programming, binary trees, Dijkstra — solve complex problems!",
    ages: "18+ ans",
    ages_en: "Ages 18+",
    color: "from-slate-600 to-gray-700",
    bg: "bg-slate-50",
    darkBg: "dark:bg-slate-950/30",
    border: "border-slate-200",
    darkBorder: "dark:border-slate-800",
    lessons: 6,
  },
];
