export interface ProjectStep {
  id: number;
  title: string;
  title_en?: string;
  description: string;
  description_en?: string;
  starterCode: string;
  starterCode_en?: string;
  expectedOutput: string;
  expectedOutput_en?: string;
  hint: string;
  hint_en?: string;
}

export interface GuidedProject {
  id: string;
  levelId: number;
  emoji: string;
  title: string;
  title_en?: string;
  description: string;
  description_en?: string;
  color: string;
  steps: ProjectStep[];
}

export const GUIDED_PROJECTS: GuidedProject[] = [
  {
    id: "robot-bavard",
    levelId: 0,
    emoji: "🤖",
    title: "Le Robot Bavard",
    title_en: "The Chatty Robot",
    description: "Crée un robot qui parle, se présente et raconte une blague ! Tu vas apprendre à utiliser print() comme un vrai programmeur.",
    description_en: "Create a robot that talks, introduces itself, and tells a joke! You'll learn to use print() like a real programmer.",
    color: "from-green-400 to-emerald-500",
    steps: [
      {
        id: 0,
        title: "Le robot se présente",
        title_en: "The robot introduces itself",
        description: "Fais dire à ton robot son nom et sa spécialité. Utilise 3 print() à la suite.",
        description_en: "Make your robot say its name and specialty. Use 3 print() in a row.",
        starterCode: '# Fais parler ton robot !\n# Il doit dire son nom, son âge (en années de création) et sa spécialité\n\nprint("Je suis...")\n',
        starterCode_en: '# Make your robot talk!\n# It should say its name, age (in creation years) and specialty\n\nprint("I am...")\n',
        expectedOutput: "Je suis ROBO-3000 !\nJ'ai 2 ans.\nMa spécialité : apprendre Python !",
        expectedOutput_en: "I am ROBO-3000!\nI am 2 years old.\nMy specialty: learning Python!",
        hint: "Écris trois lignes print() avec exactement le bon texte.",
        hint_en: "Write three print() lines with exactly the right text.",
      },
      {
        id: 1,
        title: "Le robot compte",
        title_en: "The robot counts",
        description: "Ton robot adore compter ! Fais-le compter de 1 à 5 en affichant chaque chiffre.",
        description_en: "Your robot loves to count! Make it count from 1 to 5, displaying each number.",
        starterCode: "# Le robot compte de 1 à 5\n# Une ligne par chiffre\n\nprint(1)\n",
        starterCode_en: "# The robot counts from 1 to 5\n# One line per number\n\nprint(1)\n",
        expectedOutput: "1\n2\n3\n4\n5",
        hint: "Utilise print() 5 fois, une fois pour chaque chiffre.",
        hint_en: "Use print() 5 times, once for each number.",
      },
      {
        id: 2,
        title: "Le robot raconte une blague",
        title_en: "The robot tells a joke",
        description: "Programme le robot pour qu'il raconte une blague en 2 temps : d'abord la question, puis la réponse.",
        description_en: "Program the robot to tell a joke in 2 parts: first the question, then the answer.",
        starterCode: '# La blague du robot !\nprint("Pourquoi les plongeurs plongent-ils toujours en arrière ?")\nprint("...")\n',
        starterCode_en: '# The robot\'s joke!\nprint("Why do scuba divers always dive backwards?")\nprint("...")\n',
        expectedOutput: "Pourquoi les plongeurs plongent-ils toujours en arrière ?\nParce que sinon ils tomberaient dans le bateau !",
        expectedOutput_en: "Why do scuba divers always dive backwards?\nBecause if they went forwards they'd fall into the boat!",
        hint: "Remplace les '...' par la réponse de la blague.",
        hint_en: "Replace '...' with the joke's answer.",
      },
      {
        id: 3,
        title: "Le robot se souvient",
        title_en: "The robot remembers",
        description: "Utilise des variables pour stocker le nom de l'utilisateur et le nombre de blagues racontées, puis affiche un résumé.",
        description_en: "Use variables to store the user's name and the number of jokes told, then display a summary.",
        starterCode: '# Stocke des infos dans des variables\nnom = "Alice"\nnb_blagues = 3\n\n# Affiche un message personnalisé\nprint("Bonjour " + ... + " !")\nprint("J\'ai raconté " + str(...) + " blagues aujourd\'hui.")\n',
        starterCode_en: '# Store info in variables\nname = "Alice"\nnb_jokes = 3\n\n# Display a personalized message\nprint("Hello " + ... + "!")\nprint("I told " + str(...) + " jokes today.")\n',
        expectedOutput: "Bonjour Alice !\nJ'ai raconté 3 blagues aujourd'hui.",
        expectedOutput_en: "Hello Alice!\nI told 3 jokes today.",
        hint: "Remplace les ... par les noms de variables : nom et nb_blagues. Pour les nombres, utilise str() pour les convertir en texte.",
        hint_en: "Replace ... with the variable names: name and nb_jokes. For numbers, use str() to convert them to text.",
      },
      {
        id: 4,
        title: "Le robot fait le bilan",
        title_en: "The robot reports",
        description: "Crée un programme qui calcule et affiche le bilan du robot : nombre de mots dits et moyenne de mots par blague.",
        description_en: "Create a program that calculates and displays the robot's report: number of words said and average words per joke.",
        starterCode: '# Bilan du robot bavard\nblague1 = "Pourquoi les plongeurs plongent-ils toujours en arrière ? Parce que sinon ils tomberaient dans le bateau !"\nblague2 = "Qu\'est-ce qu\'un canif ? Un petit fien !"\nblague3 = "Pourquoi le scarabée ? Parce que la betterave !"\n\nmots_total = len(blague1.split()) + len(blague2.split()) + len(blague3.split())\nmoyenne = mots_total // 3\n\nprint("Mots prononcés au total : " + str(mots_total))\nprint("Moyenne par blague : " + str(moyenne) + " mots")\n',
        starterCode_en: '# Chatty robot report\njoke1 = "Why do scuba divers always dive backwards? Because if they went forwards they\'d fall into the boat!"\njoke2 = "Why did the programmer quit? Because he didn\'t get arrays!"\njoke3 = "A SQL query walks into a bar, walks up to two tables and asks: Can I join you?"\n\ntotal_words = len(joke1.split()) + len(joke2.split()) + len(joke3.split())\naverage = total_words // 3\n\nprint("Total words spoken: " + str(total_words))\nprint("Average per joke: " + str(average) + " words")\n',
        expectedOutput: "Mots prononcés au total : 34\nMoyenne par blague : 11 mots",
        expectedOutput_en: "Total words spoken: 43\nAverage per joke: 14 words",
        hint: "split() divise une phrase en liste de mots. len() compte les éléments. // fait la division entière.",
        hint_en: "split() divides a sentence into a list of words. len() counts the elements. // does integer division.",
      },
    ],
  },
  {
    id: "devinette",
    levelId: 1,
    emoji: "🎲",
    title: "Le Jeu de Devinette",
    title_en: "The Guessing Game",
    description: "Crée un vrai jeu où l'ordinateur choisit un nombre et le joueur doit le trouver. Variables, conditions et boucles au programme !",
    description_en: "Create a real game where the computer picks a number and the player has to find it. Variables, conditions and loops on the agenda!",
    color: "from-yellow-400 to-orange-400",
    steps: [
      {
        id: 0,
        title: "Stocker le nombre secret",
        title_en: "Store the secret number",
        description: "Crée une variable `secret` qui contient le nombre 42, et affiche un message de bienvenue.",
        description_en: "Create a variable `secret` containing the number 42, and display a welcome message.",
        starterCode: "# Crée le nombre secret\nsecret = ...\nprint(\"Bienvenue dans le jeu de devinette !\")\nprint(\"J'ai choisi un nombre entre 1 et 100.\")\n",
        starterCode_en: "# Create the secret number\nsecret = ...\nprint(\"Welcome to the guessing game!\")\nprint(\"I've picked a number between 1 and 100.\")\n",
        expectedOutput: "Bienvenue dans le jeu de devinette !\nJ'ai choisi un nombre entre 1 et 100.",
        expectedOutput_en: "Welcome to the guessing game!\nI've picked a number between 1 and 100.",
        hint: "Remplace ... par le nombre 42.",
        hint_en: "Replace ... with the number 42.",
      },
      {
        id: 1,
        title: "Comparer deux nombres",
        title_en: "Compare two numbers",
        description: "Utilise une condition `if/elif/else` pour comparer `proposition = 30` avec `secret = 42`.",
        description_en: "Use an if/elif/else condition to compare `guess = 30` with `secret = 42`.",
        starterCode: "secret = 42\nproposition = 30\n\n# Compare et affiche le bon message\nif proposition == secret:\n    print(\"Bravo !\")\nelif proposition < secret:\n    print(\"...\")  # Trop petit !\nelse:\n    print(\"...\")  # Trop grand !\n",
        starterCode_en: "secret = 42\nguess = 30\n\n# Compare and display the right message\nif guess == secret:\n    print(\"Well done!\")\nelif guess < secret:\n    print(\"...\")  # Too small!\nelse:\n    print(\"...\")  # Too big!\n",
        expectedOutput: "Trop petit !",
        expectedOutput_en: "Too small!",
        hint: "Remplace les ... par 'Trop petit !' ou 'Trop grand !' selon la logique.",
        hint_en: "Replace ... with 'Too small!' or 'Too big!' according to the logic.",
      },
      {
        id: 2,
        title: "Simuler plusieurs essais",
        title_en: "Simulate several attempts",
        description: "Simule 3 essais avec une liste de propositions et affiche le résultat de chaque essai.",
        description_en: "Simulate 3 attempts with a list of guesses and display the result of each attempt.",
        starterCode: "secret = 42\nessais = [20, 60, 42]\n\nfor proposition in essais:\n    if proposition == secret:\n        print(f\"{proposition} - Bravo !\")\n    elif proposition < secret:\n        print(f\"{proposition} - ...\")  # Trop petit !\n    else:\n        print(f\"{proposition} - ...\")  # Trop grand !\n",
        starterCode_en: "secret = 42\nattempts = [20, 60, 42]\n\nfor guess in attempts:\n    if guess == secret:\n        print(f\"{guess} - Well done!\")\n    elif guess < secret:\n        print(f\"{guess} - ...\")  # Too small!\n    else:\n        print(f\"{guess} - ...\")  # Too big!\n",
        expectedOutput: "20 - Trop petit !\n60 - Trop grand !\n42 - Bravo !",
        expectedOutput_en: "20 - Too small!\n60 - Too big!\n42 - Well done!",
        hint: "Complète les ... avec 'Trop petit !' et 'Trop grand !'",
        hint_en: "Complete ... with 'Too small!' and 'Too big!'",
      },
      {
        id: 3,
        title: "Compter les tentatives",
        title_en: "Count the attempts",
        description: "Ajoute un compteur d'essais pour savoir combien de tentatives ont été nécessaires avant de trouver le nombre.",
        description_en: "Add an attempt counter to know how many tries were needed before finding the number.",
        starterCode: "secret = 42\nessais = [20, 60, 42]\ncompteur = 0\n\nfor proposition in essais:\n    compteur = compteur + 1\n    if proposition == secret:\n        print(f\"Trouvé en {compteur} essai(s) !\")\n    elif proposition < secret:\n        print(f\"Essai {compteur} : {proposition} - Trop petit !\")\n    else:\n        print(f\"Essai {compteur} : {proposition} - Trop grand !\")\n",
        starterCode_en: "secret = 42\nattempts = [20, 60, 42]\ncounter = 0\n\nfor guess in attempts:\n    counter = counter + 1\n    if guess == secret:\n        print(f\"Found in {counter} attempt(s)!\")\n    elif guess < secret:\n        print(f\"Attempt {counter}: {guess} - Too small!\")\n    else:\n        print(f\"Attempt {counter}: {guess} - Too big!\")\n",
        expectedOutput: "Essai 1 : 20 - Trop petit !\nEssai 2 : 60 - Trop grand !\nTrouvé en 3 essai(s) !",
        expectedOutput_en: "Attempt 1: 20 - Too small!\nAttempt 2: 60 - Too big!\nFound in 3 attempt(s)!",
        hint: "compteur = compteur + 1 s'écrit aussi compteur += 1. La variable s'incrémente à chaque tour de boucle.",
        hint_en: "counter = counter + 1 can also be written counter += 1. The variable increments each loop turn.",
      },
      {
        id: 4,
        title: "Score et message final",
        title_en: "Score and final message",
        description: "Calcule un score (moins d'essais = meilleur score) et affiche un message de félicitations adapté.",
        description_en: "Calculate a score (fewer attempts = better score) and display an appropriate congratulations message.",
        starterCode: "secret = 42\nessais = [20, 60, 42]\ncompteur = 0\ntrouve = False\n\nfor proposition in essais:\n    compteur += 1\n    if proposition == secret:\n        trouve = True\n        break\n\nif trouve:\n    score = max(0, 100 - (compteur - 1) * 30)\n    print(f\"Bravo ! Trouvé en {compteur} essai(s).\")\n    print(f\"Ton score : {score}/100\")\n    if score >= 100:\n        print(\"Parfait ! Premier essai !\")\n    elif score >= 70:\n        print(\"Très bien joué !\")\n    else:\n        print(\"Continue de t'entraîner !\")\n",
        starterCode_en: "secret = 42\nattempts = [20, 60, 42]\ncounter = 0\nfound = False\n\nfor guess in attempts:\n    counter += 1\n    if guess == secret:\n        found = True\n        break\n\nif found:\n    score = max(0, 100 - (counter - 1) * 30)\n    print(f\"Well done! Found in {counter} attempt(s).\")\n    print(f\"Your score: {score}/100\")\n    if score >= 100:\n        print(\"Perfect! First try!\")\n    elif score >= 70:\n        print(\"Great job!\")\n    else:\n        print(\"Keep practising!\")\n",
        expectedOutput: "Bravo ! Trouvé en 3 essai(s).\nTon score : 40/100\nContinue de t'entraîner !",
        expectedOutput_en: "Well done! Found in 3 attempt(s).\nYour score: 40/100\nKeep practising!",
        hint: "break arrête la boucle dès qu'on trouve. max(0, ...) évite un score négatif. Ici 100 - (3-1)*30 = 40.",
        hint_en: "break stops the loop as soon as you find it. max(0, ...) avoids a negative score. Here 100 - (3-1)*30 = 40.",
      },
    ],
  },
  {
    id: "carnet-contacts",
    levelId: 2,
    emoji: "📒",
    title: "Le Carnet de Contacts",
    title_en: "The Contact Book",
    description: "Construis un carnet de contacts avec des listes et des fonctions. Tu vas créer, afficher et rechercher des contacts !",
    description_en: "Build a contact book with lists and functions. You'll create, display and search for contacts!",
    color: "from-blue-400 to-cyan-500",
    steps: [
      {
        id: 0,
        title: "Créer les contacts",
        title_en: "Create the contacts",
        description: "Crée une liste `contacts` avec 3 noms et affiche-les avec leur numéro d'ordre.",
        description_en: "Create a `contacts` list with 3 names and display them with their order number.",
        starterCode: "contacts = [\"Alice\", \"Bob\", \"Charlie\"]\n\n# Affiche chaque contact avec son numéro\nfor i, nom in enumerate(contacts, 1):\n    print(f\"...\")\n",
        starterCode_en: "contacts = [\"Alice\", \"Bob\", \"Charlie\"]\n\n# Display each contact with its number\nfor i, name in enumerate(contacts, 1):\n    print(f\"...\")\n",
        expectedOutput: "1. Alice\n2. Bob\n3. Charlie",
        hint: "Dans le f-string, utilise {i} pour le numéro et {nom} pour le nom.",
        hint_en: "In the f-string, use {i} for the number and {name} for the name.",
      },
      {
        id: 1,
        title: "Fonction d'ajout",
        title_en: "Add function",
        description: "Crée une fonction `ajouter(contacts, nom)` qui ajoute un contact à la liste et affiche un message de confirmation.",
        description_en: "Create an `add(contacts, name)` function that adds a contact to the list and displays a confirmation message.",
        starterCode: "def ajouter(contacts, nom):\n    contacts.append(nom)\n    print(f\"{nom} ajouté !\")\n\ncontacts = [\"Alice\", \"Bob\"]\najouter(contacts, \"David\")\nprint(f\"Total : {len(contacts)} contacts\")\n",
        starterCode_en: "def add(contacts, name):\n    contacts.append(name)\n    print(f\"{name} added!\")\n\ncontacts = [\"Alice\", \"Bob\"]\nadd(contacts, \"David\")\nprint(f\"Total: {len(contacts)} contacts\")\n",
        expectedOutput: "David ajouté !\nTotal : 3 contacts",
        expectedOutput_en: "David added!\nTotal: 3 contacts",
        hint: "La fonction est déjà écrite ! Lance-la simplement et affiche le total.",
        hint_en: "The function is already written! Just call it and display the total.",
      },
      {
        id: 2,
        title: "Recherche de contact",
        title_en: "Search for a contact",
        description: "Crée une fonction `chercher(contacts, nom)` qui retourne True si le contact existe, False sinon.",
        description_en: "Create a `search(contacts, name)` function that returns True if the contact exists, False otherwise.",
        starterCode: "def chercher(contacts, nom):\n    return nom in contacts\n\ncontacts = [\"Alice\", \"Bob\", \"Charlie\"]\n\nif chercher(contacts, \"Bob\"):\n    print(\"Bob trouvé !\")\nelse:\n    print(\"Bob introuvable.\")\n\nif chercher(contacts, \"Zara\"):\n    print(\"Zara trouvé !\")\nelse:\n    print(\"Zara introuvable.\")\n",
        starterCode_en: "def search(contacts, name):\n    return name in contacts\n\ncontacts = [\"Alice\", \"Bob\", \"Charlie\"]\n\nif search(contacts, \"Bob\"):\n    print(\"Bob found!\")\nelse:\n    print(\"Bob not found.\")\n\nif search(contacts, \"Zara\"):\n    print(\"Zara found!\")\nelse:\n    print(\"Zara not found.\")\n",
        expectedOutput: "Bob trouvé !\nZara introuvable.",
        expectedOutput_en: "Bob found!\nZara not found.",
        hint: "La fonction chercher() utilise l'opérateur `in`. Le code est complet, lance-le !",
        hint_en: "The search() function uses the `in` operator. The code is complete, run it!",
      },
      {
        id: 3,
        title: "Trier les contacts",
        title_en: "Sort the contacts",
        description: "Trie la liste de contacts par ordre alphabétique et affiche-la numérotée.",
        description_en: "Sort the contact list alphabetically and display it numbered.",
        starterCode: "contacts = [\"Charlie\", \"Alice\", \"Bob\", \"David\"]\n\ncontacts_tries = sorted(contacts)\n\nprint(\"Carnet trié :\")\nfor i, nom in enumerate(contacts_tries, 1):\n    print(f\"  {i}. {nom}\")\n",
        starterCode_en: "contacts = [\"Charlie\", \"Alice\", \"Bob\", \"David\"]\n\nsorted_contacts = sorted(contacts)\n\nprint(\"Sorted book:\")\nfor i, name in enumerate(sorted_contacts, 1):\n    print(f\"  {i}. {name}\")\n",
        expectedOutput: "Carnet trié :\n  1. Alice\n  2. Bob\n  3. Charlie\n  4. David",
        expectedOutput_en: "Sorted book:\n  1. Alice\n  2. Bob\n  3. Charlie\n  4. David",
        hint: "sorted() retourne une nouvelle liste triée sans modifier l'originale. enumerate(liste, 1) démarre le compteur à 1.",
        hint_en: "sorted() returns a new sorted list without modifying the original. enumerate(list, 1) starts the counter at 1.",
      },
      {
        id: 4,
        title: "Supprimer un contact",
        title_en: "Delete a contact",
        description: "Crée une fonction `supprimer(contacts, nom)` qui retire un contact s'il existe, et affiche un message de confirmation.",
        description_en: "Create a `delete(contacts, name)` function that removes a contact if it exists, and displays a confirmation message.",
        starterCode: "def supprimer(contacts, nom):\n    if nom in contacts:\n        contacts.remove(nom)\n        print(f\"{nom} supprimé.\")\n    else:\n        print(f\"{nom} introuvable.\")\n\ncontacts = [\"Alice\", \"Bob\", \"Charlie\"]\nsupprimer(contacts, \"Bob\")\nsupprimer(contacts, \"Zara\")\nprint(f\"Contacts restants : {contacts}\")\n",
        starterCode_en: "def delete(contacts, name):\n    if name in contacts:\n        contacts.remove(name)\n        print(f\"{name} deleted.\")\n    else:\n        print(f\"{name} not found.\")\n\ncontacts = [\"Alice\", \"Bob\", \"Charlie\"]\ndelete(contacts, \"Bob\")\ndelete(contacts, \"Zara\")\nprint(f\"Remaining contacts: {contacts}\")\n",
        expectedOutput: "Bob supprimé.\nZara introuvable.\nContacts restants : ['Alice', 'Charlie']",
        expectedOutput_en: "Bob deleted.\nZara not found.\nRemaining contacts: ['Alice', 'Charlie']",
        hint: "remove() retire la première occurrence d'un élément. Vérifie d'abord avec `in` pour éviter une erreur.",
        hint_en: "remove() removes the first occurrence of an element. Check first with `in` to avoid an error.",
      },
    ],
  },
  {
    id: "base-eleves",
    levelId: 3,
    emoji: "🏫",
    title: "La Base de Données d'Élèves",
    title_en: "The Student Database",
    description: "Crée un système pour gérer les notes des élèves avec des dictionnaires. Ajoute, modifie et calcule les moyennes !",
    description_en: "Create a system to manage student grades using dictionaries. Add, modify and calculate averages!",
    color: "from-purple-500 to-violet-600",
    steps: [
      {
        id: 0,
        title: "Créer le dictionnaire",
        title_en: "Create the dictionary",
        description: "Crée un dictionnaire `eleves` avec 3 élèves et leurs notes, puis affiche chaque élève et sa note.",
        description_en: "Create an `students` dictionary with 3 students and their grades, then display each student and their grade.",
        starterCode: "eleves = {\n    \"Alice\": 18,\n    \"Bob\": 14,\n    \"Charlie\": 16\n}\n\nfor nom, note in eleves.items():\n    print(f\"{nom} : {note}/20\")\n",
        starterCode_en: "students = {\n    \"Alice\": 18,\n    \"Bob\": 14,\n    \"Charlie\": 16\n}\n\nfor name, grade in students.items():\n    print(f\"{name}: {grade}/20\")\n",
        expectedOutput: "Alice : 18/20\nBob : 14/20\nCharlie : 16/20",
        expectedOutput_en: "Alice: 18/20\nBob: 14/20\nCharlie: 16/20",
        hint: "Le code est prêt ! Lance-le pour voir le résultat.",
        hint_en: "The code is ready! Run it to see the result.",
      },
      {
        id: 1,
        title: "Calculer la moyenne",
        title_en: "Calculate the average",
        description: "Calcule et affiche la moyenne de toutes les notes avec 2 décimales.",
        description_en: "Calculate and display the average of all grades with 2 decimal places.",
        starterCode: "eleves = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16}\n\nnotes = list(eleves.values())\nmoyenne = sum(notes) / len(notes)\nprint(f\"Moyenne de la classe : {moyenne:.2f}/20\")\n",
        starterCode_en: "students = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16}\n\ngrades = list(students.values())\naverage = sum(grades) / len(grades)\nprint(f\"Class average: {average:.2f}/20\")\n",
        expectedOutput: "Moyenne de la classe : 16.00/20",
        expectedOutput_en: "Class average: 16.00/20",
        hint: "Utilise sum() pour la somme et len() pour le nombre d'élèves.",
        hint_en: "Use sum() for the total and len() for the number of students.",
      },
      {
        id: 2,
        title: "Trouver le meilleur",
        title_en: "Find the best",
        description: "Trouve et affiche l'élève avec la meilleure note en utilisant max().",
        description_en: "Find and display the student with the best grade using max().",
        starterCode: "eleves = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16}\n\nmeilleur = max(eleves, key=eleves.get)\nprint(f\"Meilleur élève : {meilleur} avec {eleves[meilleur]}/20\")\n",
        starterCode_en: "students = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16}\n\nbest = max(students, key=students.get)\nprint(f\"Best student: {best} with {students[best]}/20\")\n",
        expectedOutput: "Meilleur élève : Alice avec 18/20",
        expectedOutput_en: "Best student: Alice with 18/20",
        hint: "max() avec key=eleves.get trouve la clé avec la valeur maximale.",
        hint_en: "max() with key=students.get finds the key with the maximum value.",
      },
      {
        id: 3,
        title: "Classement de la classe",
        title_en: "Class ranking",
        description: "Affiche le classement complet des élèves du meilleur au moins bon, avec leur rang.",
        description_en: "Display the complete ranking of students from best to worst, with their rank.",
        starterCode: "eleves = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16, \"Diana\": 12, \"Ethan\": 19}\n\nclassement = sorted(eleves.items(), key=lambda x: x[1], reverse=True)\n\nprint(\"=== Classement ===\")\nfor rang, (nom, note) in enumerate(classement, 1):\n    medaille = \"🥇\" if rang == 1 else \"🥈\" if rang == 2 else \"🥉\" if rang == 3 else \"  \"\n    print(f\"{medaille} {rang}. {nom} : {note}/20\")\n",
        starterCode_en: "students = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16, \"Diana\": 12, \"Ethan\": 19}\n\nranking = sorted(students.items(), key=lambda x: x[1], reverse=True)\n\nprint(\"=== Ranking ===\")\nfor rank, (name, grade) in enumerate(ranking, 1):\n    medal = \"🥇\" if rank == 1 else \"🥈\" if rank == 2 else \"🥉\" if rank == 3 else \"  \"\n    print(f\"{medal} {rank}. {name}: {grade}/20\")\n",
        expectedOutput: "=== Classement ===\n🥇 1. Ethan : 19/20\n🥈 2. Alice : 18/20\n🥉 3. Charlie : 16/20\n   4. Bob : 14/20\n   5. Diana : 12/20",
        expectedOutput_en: "=== Ranking ===\n🥇 1. Ethan: 19/20\n🥈 2. Alice: 18/20\n🥉 3. Charlie: 16/20\n   4. Bob: 14/20\n   5. Diana: 12/20",
        hint: "sorted() avec reverse=True trie du plus grand au plus petit. lambda x: x[1] trie par la note (deuxième élément du tuple).",
        hint_en: "sorted() with reverse=True sorts from largest to smallest. lambda x: x[1] sorts by grade (second element of the tuple).",
      },
      {
        id: 4,
        title: "Élèves sous la moyenne",
        title_en: "Students below average",
        description: "Identifie les élèves dont la note est inférieure à la moyenne et affiche une liste de ceux qui ont besoin d'aide.",
        description_en: "Identify students whose grade is below average and display a list of those who need help.",
        starterCode: "eleves = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16, \"Diana\": 12, \"Ethan\": 19}\n\nnotes = list(eleves.values())\nmoyenne = sum(notes) / len(notes)\nprint(f\"Moyenne : {moyenne:.1f}/20\")\n\nsous_moyenne = [nom for nom, note in eleves.items() if note < moyenne]\nprint(f\"Élèves sous la moyenne : {sous_moyenne}\")\nprint(f\"Nombre d'élèves à aider : {len(sous_moyenne)}\")\n",
        starterCode_en: "students = {\"Alice\": 18, \"Bob\": 14, \"Charlie\": 16, \"Diana\": 12, \"Ethan\": 19}\n\ngrades = list(students.values())\naverage = sum(grades) / len(grades)\nprint(f\"Average: {average:.1f}/20\")\n\nbelow_average = [name for name, grade in students.items() if grade < average]\nprint(f\"Students below average: {below_average}\")\nprint(f\"Number of students to help: {len(below_average)}\")\n",
        expectedOutput: "Moyenne : 15.8/20\nÉlèves sous la moyenne : ['Bob', 'Diana']\nNombre d'élèves à aider : 2",
        expectedOutput_en: "Average: 15.8/20\nStudents below average: ['Bob', 'Diana']\nNumber of students to help: 2",
        hint: "Une compréhension de liste [x for x in liste if condition] filtre les éléments. Ici on filtre les noms dont la note < moyenne.",
        hint_en: "A list comprehension [x for x in list if condition] filters elements. Here we filter names whose grade < average.",
      },
    ],
  },
  {
    id: "jeu-rpg",
    levelId: 4,
    emoji: "⚔️",
    title: "Le Mini RPG",
    title_en: "The Mini RPG",
    description: "Crée un mini jeu de rôle avec des classes Python ! Un héros combat un monstre, avec des points de vie et des attaques.",
    description_en: "Create a mini role-playing game with Python classes! A hero fights a monster, with hit points and attacks.",
    color: "from-pink-500 to-rose-600",
    steps: [
      {
        id: 0,
        title: "La classe Personnage",
        title_en: "The Character class",
        description: "Crée une classe `Personnage` avec un nom et des points de vie, et une méthode `present()` qui se présente.",
        description_en: "Create a `Character` class with a name and hit points, and a `present()` method that introduces itself.",
        starterCode: "class Personnage:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\n    def present(self):\n        print(f\"{self.nom} ({self.pv} PV)\")\n\nheros = Personnage(\"Aria\", 100)\nmonster = Personnage(\"Dragon\", 80)\nheros.present()\nmonster.present()\n",
        starterCode_en: "class Character:\n    def __init__(self, name, hp):\n        self.name = name\n        self.hp = hp\n\n    def present(self):\n        print(f\"{self.name} ({self.hp} HP)\")\n\nhero = Character(\"Aria\", 100)\nmonster = Character(\"Dragon\", 80)\nhero.present()\nmonster.present()\n",
        expectedOutput: "Aria (100 PV)\nDragon (80 PV)",
        expectedOutput_en: "Aria (100 HP)\nDragon (80 HP)",
        hint: "Le code est complet ! Lance-le pour voir tes personnages.",
        hint_en: "The code is complete! Run it to see your characters.",
      },
      {
        id: 1,
        title: "Méthode d'attaque",
        title_en: "Attack method",
        description: "Ajoute une méthode `attaquer(cible, degats)` qui réduit les PV de la cible et affiche le résultat.",
        description_en: "Add an `attack(target, damage)` method that reduces the target's HP and displays the result.",
        starterCode: "class Personnage:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\n    def attaquer(self, cible, degats):\n        cible.pv -= degats\n        print(f\"{self.nom} attaque {cible.nom} pour {degats} dégâts ! ({cible.pv} PV restants)\")\n\nheros = Personnage(\"Aria\", 100)\ndragon = Personnage(\"Dragon\", 80)\nheros.attaquer(dragon, 25)\ndragon.attaquer(heros, 15)\n",
        starterCode_en: "class Character:\n    def __init__(self, name, hp):\n        self.name = name\n        self.hp = hp\n\n    def attack(self, target, damage):\n        target.hp -= damage\n        print(f\"{self.name} attacks {target.name} for {damage} damage! ({target.hp} HP remaining)\")\n\nhero = Character(\"Aria\", 100)\ndragon = Character(\"Dragon\", 80)\nhero.attack(dragon, 25)\ndragon.attack(hero, 15)\n",
        expectedOutput: "Aria attaque Dragon pour 25 dégâts ! (55 PV restants)\nDragon attaque Aria pour 15 dégâts ! (85 PV restants)",
        expectedOutput_en: "Aria attacks Dragon for 25 damage! (55 HP remaining)\nDragon attacks Aria for 15 damage! (85 HP remaining)",
        hint: "Utilise cible.pv -= degats pour réduire les PV.",
        hint_en: "Use target.hp -= damage to reduce HP.",
      },
      {
        id: 2,
        title: "Est-ce vivant ?",
        title_en: "Is it alive?",
        description: "Ajoute une propriété `est_vivant` et teste si les personnages sont en vie après des attaques.",
        description_en: "Add an `is_alive` property and test if the characters are alive after attacks.",
        starterCode: "class Personnage:\n    def __init__(self, nom, pv):\n        self.nom = nom\n        self.pv = pv\n\n    @property\n    def est_vivant(self):\n        return self.pv > 0\n\nheros = Personnage(\"Aria\", 100)\nenemi = Personnage(\"Goblin\", 20)\nenemi.pv -= 30  # attaque fatale\n\nprint(f\"Aria vivante : {heros.est_vivant}\")\nprint(f\"Goblin vivant : {enemi.est_vivant}\")\n",
        starterCode_en: "class Character:\n    def __init__(self, name, hp):\n        self.name = name\n        self.hp = hp\n\n    @property\n    def is_alive(self):\n        return self.hp > 0\n\nhero = Character(\"Aria\", 100)\nenemy = Character(\"Goblin\", 20)\nenemy.hp -= 30  # fatal attack\n\nprint(f\"Aria alive: {hero.is_alive}\")\nprint(f\"Goblin alive: {enemy.is_alive}\")\n",
        expectedOutput: "Aria vivante : True\nGoblin vivant : False",
        expectedOutput_en: "Aria alive: True\nGoblin alive: False",
        hint: "Après avoir retiré 30 PV au Goblin (qui en a 20), ses PV sont négatifs → est_vivant = False.",
        hint_en: "After removing 30 HP from the Goblin (who has 20), its HP is negative → is_alive = False.",
      },
      {
        id: 3,
        title: "Combat tour par tour",
        title_en: "Turn-based combat",
        description: "Simule un combat complet entre le héros et le dragon : ils s'attaquent à tour de rôle jusqu'à ce que l'un d'eux tombe.",
        description_en: "Simulate a full fight between the hero and the dragon: they attack each other in turns until one of them falls.",
        starterCode: "class Personnage:\n    def __init__(self, nom, pv, force):\n        self.nom = nom\n        self.pv = pv\n        self.force = force\n\n    @property\n    def est_vivant(self):\n        return self.pv > 0\n\nheros = Personnage(\"Aria\", 50, 15)\ndragon = Personnage(\"Dragon\", 50, 12)\ntour = 1\n\nwhile heros.est_vivant and dragon.est_vivant:\n    dragon.pv -= heros.force\n    heros.pv -= dragon.force\n    print(f\"Tour {tour} — Aria: {max(0, heros.pv)} PV | Dragon: {max(0, dragon.pv)} PV\")\n    tour += 1\n\nif heros.est_vivant:\n    print(\"Aria a gagné !\")\nelse:\n    print(\"Le Dragon a gagné !\")\n",
        starterCode_en: "class Character:\n    def __init__(self, name, hp, strength):\n        self.name = name\n        self.hp = hp\n        self.strength = strength\n\n    @property\n    def is_alive(self):\n        return self.hp > 0\n\nhero = Character(\"Aria\", 50, 15)\ndragon = Character(\"Dragon\", 50, 12)\nturn = 1\n\nwhile hero.is_alive and dragon.is_alive:\n    dragon.hp -= hero.strength\n    hero.hp -= dragon.strength\n    print(f\"Turn {turn} — Aria: {max(0, hero.hp)} HP | Dragon: {max(0, dragon.hp)} HP\")\n    turn += 1\n\nif hero.is_alive:\n    print(\"Aria won!\")\nelse:\n    print(\"The Dragon won!\")\n",
        expectedOutput: "Tour 1 — Aria: 38 PV | Dragon: 35 PV\nTour 2 — Aria: 26 PV | Dragon: 20 PV\nTour 3 — Aria: 14 PV | Dragon: 5 PV\nTour 4 — Aria: 2 PV | Dragon: 0 PV\nAria a gagné !",
        expectedOutput_en: "Turn 1 — Aria: 38 HP | Dragon: 35 HP\nTurn 2 — Aria: 26 HP | Dragon: 20 HP\nTurn 3 — Aria: 14 HP | Dragon: 5 HP\nTurn 4 — Aria: 2 HP | Dragon: 0 HP\nAria won!",
        hint: "La boucle while continue tant que les deux sont en vie. max(0, pv) évite d'afficher des PV négatifs.",
        hint_en: "The while loop continues as long as both are alive. max(0, hp) avoids displaying negative HP.",
      },
      {
        id: 4,
        title: "Héritage — la classe Mage",
        title_en: "Inheritance — the Mage class",
        description: "Crée une classe Mage qui hérite de Personnage et ajoute un sort magique qui fait le double des dégâts normaux.",
        description_en: "Create a Mage class that inherits from Character and adds a magic spell that does double the normal damage.",
        starterCode: "class Personnage:\n    def __init__(self, nom, pv, force):\n        self.nom = nom\n        self.pv = pv\n        self.force = force\n\n    def attaquer(self, cible):\n        cible.pv -= self.force\n        print(f\"{self.nom} attaque {cible.nom} pour {self.force} dégâts !\")\n\nclass Mage(Personnage):\n    def sort(self, cible):\n        degats = self.force * 2\n        cible.pv -= degats\n        print(f\"{self.nom} lance un sort sur {cible.nom} pour {degats} dégâts magiques !\")\n\nmage = Mage(\"Merlin\", 60, 10)\ndragon = Personnage(\"Dragon\", 80, 15)\n\nmage.attaquer(dragon)\nmage.sort(dragon)\nprint(f\"Dragon PV restants : {dragon.pv}\")\n",
        starterCode_en: "class Character:\n    def __init__(self, name, hp, strength):\n        self.name = name\n        self.hp = hp\n        self.strength = strength\n\n    def attack(self, target):\n        target.hp -= self.strength\n        print(f\"{self.name} attacks {target.name} for {self.strength} damage!\")\n\nclass Mage(Character):\n    def spell(self, target):\n        damage = self.strength * 2\n        target.hp -= damage\n        print(f\"{self.name} casts a spell on {target.name} for {damage} magic damage!\")\n\nmage = Mage(\"Merlin\", 60, 10)\ndragon = Character(\"Dragon\", 80, 15)\n\nmage.attack(dragon)\nmage.spell(dragon)\nprint(f\"Dragon HP remaining: {dragon.hp}\")\n",
        expectedOutput: "Merlin attaque Dragon pour 10 dégâts !\nMerlin lance un sort sur Dragon pour 20 dégâts magiques !\nDragon PV restants : 50",
        expectedOutput_en: "Merlin attacks Dragon for 10 damage!\nMerlin casts a spell on Dragon for 20 magic damage!\nDragon HP remaining: 50",
        hint: "class Mage(Personnage) signifie que Mage hérite de toutes les méthodes de Personnage. Tu peux appeler mage.attaquer() même si tu ne l'as pas réécrite dans Mage.",
        hint_en: "class Mage(Character) means Mage inherits all of Character's methods. You can call mage.attack() even if you didn't rewrite it in Mage.",
      },
    ],
  },
  {
    id: "analyseur-texte",
    levelId: 5,
    emoji: "🔍",
    title: "L'Analyseur de Texte",
    title_en: "The Text Analyzer",
    description: "Analyse des textes comme un data scientist ! Compte les mots, trouve les plus fréquents et travaille avec des collections avancées.",
    description_en: "Analyze texts like a data scientist! Count words, find the most frequent ones and work with advanced collections.",
    color: "from-cyan-500 to-blue-600",
    steps: [
      {
        id: 0,
        title: "Compter les mots",
        title_en: "Count the words",
        description: "Compte le nombre de mots dans une phrase et affiche le résultat.",
        description_en: "Count the number of words in a sentence and display the result.",
        starterCode: "texte = \"Python est un langage de programmation puissant et simple\"\n\nmots = texte.split()\nprint(f\"Nombre de mots : {len(mots)}\")\n",
        starterCode_en: "text = \"Python is a powerful and simple programming language\"\n\nwords = text.split()\nprint(f\"Number of words: {len(words)}\")\n",
        expectedOutput: "Nombre de mots : 9",
        expectedOutput_en: "Number of words: 9",
        hint: "split() découpe le texte en liste de mots. len() compte les éléments.",
        hint_en: "split() splits the text into a list of words. len() counts the elements.",
      },
      {
        id: 1,
        title: "Fréquence des mots",
        title_en: "Word frequency",
        description: "Utilise un dictionnaire pour compter combien de fois chaque mot apparaît dans le texte.",
        description_en: "Use a dictionary to count how many times each word appears in the text.",
        starterCode: "from collections import Counter\n\ntexte = \"le chat mange le poisson et le chien mange aussi\"\nmots = texte.split()\nfreq = Counter(mots)\n\nfor mot, count in freq.most_common(3):\n    print(f\"{mot} : {count}x\")\n",
        starterCode_en: "from collections import Counter\n\ntext = \"the cat eats the fish and the dog eats too\"\nwords = text.split()\nfreq = Counter(words)\n\nfor word, count in freq.most_common(3):\n    print(f\"{word} : {count}x\")\n",
        expectedOutput: "le : 3x\nmange : 2x\nchat : 1x",
        expectedOutput_en: "the : 3x\neats : 2x\ncat : 1x",
        hint: "Counter() compte automatiquement les occurrences. most_common(3) retourne les 3 plus fréquents.",
        hint_en: "Counter() counts occurrences automatically. most_common(3) returns the 3 most frequent.",
      },
      {
        id: 2,
        title: "Mots uniques",
        title_en: "Unique words",
        description: "Trouve le nombre de mots uniques (sans doublons) dans le texte.",
        description_en: "Find the number of unique words (without duplicates) in the text.",
        starterCode: "texte = \"le chat mange le poisson et le chien mange aussi\"\nmots = texte.split()\nuniques = set(mots)\nprint(f\"Mots uniques : {len(uniques)}\")\nprint(f\"Mots uniques triés : {sorted(uniques)}\")\n",
        starterCode_en: "text = \"the cat eats the fish and the dog eats also\"\nwords = text.split()\nunique = set(words)\nprint(f\"Unique words: {len(unique)}\")\nprint(f\"Sorted unique words: {sorted(unique)}\")\n",
        expectedOutput: "Mots uniques : 7\nMots uniques triés : ['aussi', 'chien', 'chat', 'et', 'le', 'mange', 'poisson']",
        expectedOutput_en: "Unique words: 7\nSorted unique words: ['also', 'and', 'cat', 'dog', 'eats', 'fish', 'the']",
        hint: "set() élimine les doublons. sorted() trie par ordre alphabétique.",
        hint_en: "set() eliminates duplicates. sorted() sorts alphabetically.",
      },
      {
        id: 3,
        title: "Longueur des phrases",
        title_en: "Sentence length",
        description: "Découpe un texte en phrases et calcule la longueur moyenne de chaque phrase (en nombre de mots).",
        description_en: "Split a text into sentences and calculate the average length of each sentence (in number of words).",
        starterCode: "texte = \"Python est puissant. Il est simple à apprendre. Les enfants adorent coder. C'est vraiment super !\"\n\nphrase_separateurs = texte.replace(\"!\", \".\").replace(\"?\", \".\")\nphrases = [p.strip() for p in phrase_separateurs.split(\".\") if p.strip()]\n\nprint(f\"Nombre de phrases : {len(phrases)}\")\nfor i, phrase in enumerate(phrases, 1):\n    nb_mots = len(phrase.split())\n    print(f\"  Phrase {i} : {nb_mots} mots\")\n\nmoyenne = sum(len(p.split()) for p in phrases) / len(phrases)\nprint(f\"Longueur moyenne : {moyenne:.1f} mots/phrase\")\n",
        starterCode_en: "text = \"Python is powerful. It is easy to learn. Children love coding. It is really great!\"\n\nsep = text.replace(\"!\", \".\").replace(\"?\", \".\")\nsentences = [s.strip() for s in sep.split(\".\") if s.strip()]\n\nprint(f\"Number of sentences: {len(sentences)}\")\nfor i, sentence in enumerate(sentences, 1):\n    nb_words = len(sentence.split())\n    print(f\"  Sentence {i}: {nb_words} words\")\n\naverage = sum(len(s.split()) for s in sentences) / len(sentences)\nprint(f\"Average length: {average:.1f} words/sentence\")\n",
        expectedOutput: "Nombre de phrases : 4\n  Phrase 1 : 3 mots\n  Phrase 2 : 5 mots\n  Phrase 3 : 4 mots\n  Phrase 4 : 3 mots\nLongueur moyenne : 3.8 mots/phrase",
        expectedOutput_en: "Number of sentences: 4\n  Sentence 1: 3 words\n  Sentence 2: 5 words\n  Sentence 3: 4 words\n  Sentence 4: 3 words\nAverage length: 3.8 words/sentence",
        hint: "replace() remplace un caractère par un autre. split(\".\") coupe à chaque point. strip() enlève les espaces en début/fin.",
        hint_en: "replace() replaces one character with another. split('.') splits at each period. strip() removes leading/trailing spaces.",
      },
      {
        id: 4,
        title: "Rapport complet",
        title_en: "Full report",
        description: "Génère un rapport statistique complet du texte : mots totaux, uniques, phrases, mot le plus long et le plus fréquent.",
        description_en: "Generate a complete statistical report of the text: total words, unique words, sentences, longest word and most frequent.",
        starterCode: "from collections import Counter\n\ntexte = \"le petit chat noir mange le poisson et le grand chien mange aussi\"\nmots = texte.split()\n\nnb_total = len(mots)\nnb_uniques = len(set(mots))\nmot_long = max(mots, key=len)\nmot_frequent = Counter(mots).most_common(1)[0]\n\nprint(\"=== Rapport d'analyse ===\")\nprint(f\"Mots total    : {nb_total}\")\nprint(f\"Mots uniques  : {nb_uniques}\")\nprint(f\"Mot le plus long  : '{mot_long}' ({len(mot_long)} lettres)\")\nprint(f\"Mot le plus fréquent : '{mot_frequent[0]}' ({mot_frequent[1]}x)\")\n",
        starterCode_en: "from collections import Counter\n\ntext = \"le petit chat noir mange le poisson et le grand chien mange aussi\"\nwords = text.split()\n\ntotal = len(words)\nunique = len(set(words))\nlongest = max(words, key=len)\nmost_frequent = Counter(words).most_common(1)[0]\n\nprint(\"=== Analysis report ===\")\nprint(f\"Total words    : {total}\")\nprint(f\"Unique words   : {unique}\")\nprint(f\"Longest word   : '{longest}' ({len(longest)} letters)\")\nprint(f\"Most frequent  : '{most_frequent[0]}' ({most_frequent[1]}x)\")\n",
        expectedOutput: "=== Rapport d'analyse ===\nMots total    : 13\nMots uniques  : 10\nMot le plus long  : 'poisson' (7 lettres)\nMot le plus fréquent : 'le' (3x)",
        expectedOutput_en: "=== Analysis report ===\nTotal words    : 13\nUnique words   : 10\nLongest word   : 'poisson' (7 letters)\nMost frequent  : 'le' (3x)",
        hint: "max(mots, key=len) trouve le mot le plus long. most_common(1)[0] retourne un tuple (mot, compte) du mot le plus fréquent.",
        hint_en: "max(words, key=len) finds the longest word. most_common(1)[0] returns a (word, count) tuple of the most frequent word.",
      },
    ],
  },
];

const PROGRESS_KEY = "pythonkids_projects_progress";

interface ProjectProgress {
  [projectId: string]: number; // index de la dernière étape complétée + 1
}

export function getProjectsProgress(): ProjectProgress {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(localStorage.getItem(PROGRESS_KEY) ?? "{}") as ProjectProgress;
  } catch {
    return {};
  }
}

export function completeProjectStep(projectId: string, stepId: number) {
  const prog = getProjectsProgress();
  prog[projectId] = Math.max(prog[projectId] ?? 0, stepId + 1);
  localStorage.setItem(PROGRESS_KEY, JSON.stringify(prog));
}

export function getProjectStepsDone(projectId: string): number {
  return getProjectsProgress()[projectId] ?? 0;
}
